"use client";
import React, { useEffect, useRef } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ScanLog } from "../../types/scanlog";
import { ROUND_TIMES } from "./roundtime";
import { LOGO_BASE64 } from "./logoBase64";

interface PatrolReportPDFProps {
  logs: ScanLog[];
  shifts: any[];
  campusCode: string;
  campusName: string;
  campusAddress: string;
  reportDate: string;
  generatedBy: string;
}

const PatrolReportPDF: React.FC<PatrolReportPDFProps> = ({
  logs,
  shifts,
  campusCode,
  campusName,
  campusAddress,
  reportDate,
  generatedBy,
}) => {
  const generatedRef = useRef(false);

  useEffect(() => {
    if (generatedRef.current) return;
    if (!logs || logs.length === 0) return;
    if (!Object.keys(ROUND_TIMES).length) return;
    if (!generatedBy || generatedBy.trim() === "") return;
    generatedRef.current = true;
    try {
      generatePDF();
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Failed to generate PDF. Please check the console for details.");
    }
  }, [logs, campusCode, campusName, campusAddress, reportDate, generatedBy]);

  const normalizeStatus = (status?: string | null): string => {
    if (!status) return "No Data";
    const s = status.toLowerCase().trim();
    if (s === "success" || s === "completed" || s === "done") return "SUCCESS";
    if (s === "missed") return "MISSED";
    if (s === "pending") return "PENDING";
    return "No Data";
  };

  const generatePDF = () => {
    const doc = new jsPDF("landscape", "pt", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 30;

    let totalScans = logs.length;
    let completedScans = 0;
    let missedScans = 0;

    // Group logs by round
    const logsByRound: Record<string, ScanLog[]> = {};
    logs.forEach(log => {
      const r = log.round?.toString() || "Unknown";
      if (!logsByRound[r]) logsByRound[r] = [];
      logsByRound[r].push(log);
      
      const st = normalizeStatus(log.status);
      if (st === "SUCCESS") completedScans++;
      if (st === "MISSED") missedScans++;
    });

    const pageCountRef = { current: 1 };

    const decoratePage = (pageNum: number) => {
      doc.setPage(pageNum);
      // Border
      doc.setDrawColor(0);
      doc.setLineWidth(2);
      doc.rect(15, 15, pageWidth - 30, pageHeight - 30);

      // Footer (Page numbers will be added at the end)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(0);
      doc.text("Authorized By: ____________________", margin, pageHeight - margin - 10);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Report Generated on: ${new Date().toLocaleString()}`, margin, pageHeight - margin + 2);
    };

    // ---------------- PAGE 1 INITIALIZATION ----------------
    decoratePage(1);

    if (LOGO_BASE64) {
      try { doc.addImage(LOGO_BASE64, "PNG", pageWidth / 2 - 30, 25, 60, 60); } catch (e) {}
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(0);
    doc.text("OFFICIAL SECURITY AUDIT REPORT", pageWidth / 2, 105, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text(`${campusName} | ${campusAddress} | Code: ${campusCode}`, pageWidth / 2, 120, { align: "center" });

    // Summary Box
    doc.setFillColor("#F8FAFC");
    doc.setDrawColor("#E2E8F0");
    doc.setLineWidth(1);
    doc.rect(margin, 135, pageWidth - (margin * 2), 35, "FD");

    doc.setFontSize(9);
    doc.setTextColor(40);
    doc.text(`Report Date: ${reportDate}`, margin + 10, 150);
    doc.text(`Generated By: ${generatedBy}`, margin + 10, 162);

    doc.setFont("helvetica", "bold");
    doc.text(`Total Checkpoints: ${totalScans}`, pageWidth - margin - 350, 156);
    doc.setTextColor("#16A34A");
    doc.text(`Completed: ${completedScans}`, pageWidth - margin - 220, 156);
    doc.setTextColor("#DC2626");
    doc.text(`Missed: ${missedScans}`, pageWidth - margin - 100, 156);

    let currentY = 200;

    // ---------------- DRAW TABLES PER ROUND ----------------
    Object.keys(logsByRound)
      .sort((a, b) => Number(a) - Number(b))
      .forEach((roundStr) => {
        
        // If we are too close to bottom before starting a round, push to next page
        if (currentY > pageHeight - 120) {
          doc.addPage();
          pageCountRef.current++;
          decoratePage(pageCountRef.current);
          currentY = 60;
        }

        const roundTimeStr = ROUND_TIMES[Number(roundStr)] 
          ? `${ROUND_TIMES[Number(roundStr)].start} - ${ROUND_TIMES[Number(roundStr)].end}`
          : "";

        // Round Sub-Header
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(40);
        doc.text(`Round ${roundStr} ${roundTimeStr ? `(${roundTimeStr})` : ""}`, margin, currentY);
        currentY += 15;

        const tableData = logsByRound[roundStr].map((log, index) => {
          const status = normalizeStatus(log.status);
          return [
            (index + 1).toString(),
            log.qr_name || "-",
            log.guard_name || "-",
            log.scan_time ? new Date(log.scan_time).toLocaleTimeString() : "-",
            log.lat != null ? String(log.lat) : "-",
            log.lon != null ? String(log.lon) : "-",
            status
          ];
        });

        autoTable(doc, {
          startY: currentY,
          margin: { right: margin, left: margin, bottom: 60 },
          head: [["S.No", "QR Checkpoint", "Security Name", "Time Scanned", "Latitude", "Longitude", "Status"]],
          body: tableData,
          theme: "grid",
          headStyles: { fillColor: "#4F46E5", textColor: "#FFFFFF", fontStyle: "bold", halign: "center", valign: "middle" },
          styles: { font: "helvetica", fontSize: 10, valign: "middle", cellPadding: 6, halign: "center" },
          columnStyles: {
            1: { halign: "left" }, // QR Checkpoint name aligned left
            2: { halign: "left" }, // Security Name aligned left
            6: { fontStyle: "bold" },
          },
          didParseCell: (data) => {
            if (data.section === "body" && data.column.index === 6) {
              const status = data.cell.raw;
              if (status === "MISSED") {
                data.cell.styles.fillColor = "#FEE2E2";
                data.cell.styles.textColor = "#DC2626";
              } else if (status === "SUCCESS") {
                data.cell.styles.fillColor = "#DCFCE7";
                data.cell.styles.textColor = "#16A34A";
              } else if (status === "PENDING") {
                data.cell.styles.fillColor = "#FEF3C7";
                data.cell.styles.textColor = "#D97706";
              }
            }
          },
          willDrawCell: (data) => {
            if (data.section === "body") {
              // Safely read status from the cell's raw value, falling back gracefully
              const statusCell = data.row.cells[6];
              const status = statusCell ? statusCell.raw : "";
              if (status === "MISSED") {
                doc.setFillColor("#FEE2E2");
                doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, "F");
              }
            }
          },
          didDrawPage: (data) => {
            // If autoTable creates a new page, decorate it!
            if (data.pageNumber > pageCountRef.current) {
              pageCountRef.current = data.pageNumber;
              decoratePage(pageCountRef.current);
            }
          }
        });

        currentY = ((doc as any).lastAutoTable?.finalY ?? currentY) + 35;
      });

    // ---------------- FINAL PASS: PAGE NUMBERS ----------------
    for (let i = 1; i <= pageCountRef.current; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCountRef.current}`, pageWidth - margin - 40, pageHeight - margin + 2);
    }

    doc.save(`Security_Audit_Report_${reportDate}.pdf`);
  };

  return null;
};

export default PatrolReportPDF;
