"use client";

import React, { useEffect, useRef } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { ScanLog } from "../../types/scanlog";
import { ROUND_TIMES } from "./roundtime";


import { LOGO_BASE64 } from "./logoBase64";


// ================= Props =================
interface PatrolReportPDFProps {
  logs: ScanLog[];
  shifts: any[];

  campusCode: string;
  campusName: string;
  campusAddress: string;

  reportDate: string;
  generatedBy: string;
}


// ================= Component =================
const PatrolReportPDF: React.FC<PatrolReportPDFProps> = ({
  logs,
  shifts,
  campusCode,
  campusName,
  campusAddress,
  reportDate,
  generatedBy,
}) => {

  // Prevent double generation (Strict Mode)
  const generatedRef = useRef(false);


  // ================= Auto Generate =================
  useEffect(() => {

    // Already generated
    if (generatedRef.current) return;

    // No data
    if (!logs || logs.length === 0) return;

    // No rounds
    if (!Object.keys(ROUND_TIMES).length) return;

    // ✅ WAIT FOR USER NAME
    if (!generatedBy || generatedBy.trim() === "") return;

    generatedRef.current = true;

    generatePDF();

  }, [
    logs,
    campusCode,
    campusName,
    campusAddress,
    reportDate,
    generatedBy,
  ]);


  // ================= Status Normalizer =================
  const normalizeStatus = (status?: string | null): string => {

    if (!status) return "No Data";

    const s = status.toLowerCase().trim();

    if (s === "success" || s === "completed" || s === "done") {
      return "SUCCESS";
    }

    if (s === "missed") {
      return "MISSED";
    }

    if (s === "pending") {
      return "PENDING";
    }

    return "No Data";
  };


  // ================= Border =================
  const drawBorder = (doc: jsPDF) => {

    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();

    doc.setDrawColor(0, 0, 180);
    doc.setLineWidth(0.8);

    doc.rect(8, 8, w - 16, h - 16);
  };


  // ================= Generate =================
  const generatePDF = () => {

    const doc = new jsPDF();

    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();


    // Font
    doc.setFont("times", "bold");


    // Border
    drawBorder(doc);


    // ================= Header Drawer =================
    const drawHeader = (targetDoc: jsPDF, targetDate: string) => {
      
      try {
        targetDoc.addImage(LOGO_BASE64, "JPEG", 14, 12, 28, 28);
      } catch (e) {
        console.warn("Could not load logo to PDF", e);
      }
      
      targetDoc.setTextColor(0, 0, 150);
      targetDoc.setFont("times", "bold");
      targetDoc.setFontSize(20);
      targetDoc.text("SECURITY PATROL REPORT", width / 2, 20, { align: "center" });

      targetDoc.setFontSize(16);
      targetDoc.text(campusName.toUpperCase(), width / 2, 30, {
        align: "center",
      });

      targetDoc.setFont("times", "normal");
      targetDoc.setFontSize(11);

      // Address
      targetDoc.text(campusAddress.toUpperCase(), width / 2, 38, {
        align: "center",
      });

      // Meta
      targetDoc.setFont("times", "bold");
      targetDoc.setFontSize(13);
      targetDoc.setTextColor(0, 0, 150);
      targetDoc.text(`DATE : ${targetDate}`.toUpperCase(), 14, 50);

      // ✅ REAL USER NAME ALWAYS
      targetDoc.setFont("times", "normal");
      targetDoc.setFontSize(11);
      targetDoc.setTextColor(40);
      targetDoc.text(`GENERATED BY : ${generatedBy}`.toUpperCase(), 14, 57);
      targetDoc.text(`GENERATED AT : ${new Date().toLocaleString()}`.toUpperCase(), 14, 63);
    };


    let y = 72;


    // ================= Group by Date first, then Round =================
    const dates = [...new Set(logs.map((l) => l.date || reportDate))].sort();

    // ================= Grand Summary for Multi-Day Reports =================
    if (dates.length > 1) {
      drawHeader(doc, "MONTHLY GRAND SUMMARY");
      let grandY = 72;

      const isTimeInShift = (time: string, start: string, end: string) => {
        if (!time || !start || !end) return false;
        const t = time.substring(0, 5);
        const s = start.substring(0, 5);
        const e = end.substring(0, 5);
        if (s <= e) return t >= s && t < e;
        return t >= s || t < e;
      };

      const shiftsToProcess = (shifts && shifts.length > 0) 
        ? shifts 
        : [{ shift_name: "ALL DAY", start_time: "00:00:00", end_time: "24:00:00" }];

      shiftsToProcess.forEach(shift => {
        const shiftLogs = shiftsToProcess.length === 1 && shift.shift_name === "ALL DAY"
          ? logs
          : logs.filter(l => {
              const roundTime = ROUND_TIMES[l.round];
              return roundTime && isTimeInShift(roundTime.start, shift.start_time, shift.end_time);
            });

        if (shiftLogs.length === 0) return;

        const grandGuardMap: Record<string, { scanned: number, missed: number }> = {};
        
        shiftLogs.forEach(r => {
          const status = normalizeStatus(r.status);
          if (status === 'SUCCESS' || status === 'MISSED') {
            const guardsList = (r.guard_name || 'Unknown').split(',').map(name => name.trim()).filter(Boolean);
            guardsList.forEach(g => {
              if (!grandGuardMap[g]) grandGuardMap[g] = { scanned: 0, missed: 0 };
              if (status === 'SUCCESS') grandGuardMap[g].scanned++;
              else grandGuardMap[g].missed++;
            });
          }
        });
        
        const grandSummaryRows = Object.entries(grandGuardMap)
          .filter(([name, stats]) => name !== 'Unknown' || stats.scanned > 0 || stats.missed > 0)
          .sort(([, aStats], [, bStats]) => {
              const aTotal = aStats.scanned + aStats.missed;
              const bTotal = bStats.scanned + bStats.missed;
              const aPct = aTotal > 0 ? (aStats.scanned / aTotal) : 0;
              const bPct = bTotal > 0 ? (bStats.scanned / bTotal) : 0;
              if (bPct !== aPct) return bPct - aPct;
              return bStats.scanned - aStats.scanned;
          })
          .map(([name, stats]) => {
             const total = stats.scanned + stats.missed;
             const pct = total > 0 ? Math.round((stats.scanned / total) * 100) : 0;
             return [name.toUpperCase(), String(stats.scanned), String(stats.missed), String(total), `${pct}%`];
          });

        if (grandSummaryRows.length > 0) {
          if (grandY > height - 60) {
              doc.addPage();
              drawBorder(doc);
              grandY = 20;
          }

          doc.setFont("times", "bold");
          doc.setFontSize(14);
          doc.setTextColor(0, 0, 150);
          
          const shiftTitle = `OVERALL PERFORMANCE - ${shift.shift_name}`;
          doc.text(shiftTitle.toUpperCase(), 14, grandY);
          grandY += 6;

          autoTable(doc, {
              startY: grandY,
              head: [["GUARD NAME", "SUCCESSFUL SCANS", "MISSED SCANS", "TOTAL ASSIGNED", "SUCCESS RATE"]],
              body: grandSummaryRows,
              theme: "grid",
              styles: { font: "times", fontSize: 10, cellPadding: 3 },
              headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: "bold" },
              alternateRowStyles: { fillColor: [245, 248, 255] },
              columnStyles: { 1: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' }, 4: { halign: 'center' } },
              didParseCell: (data) => {
                if (data.section === "body") {
                  if (data.column.index === 4) {
                    const pct = parseInt(String(data.cell.raw));
                    if (pct >= 90) { data.cell.styles.textColor = [0, 150, 0]; data.cell.styles.fontStyle = "bold"; }
                    else if (pct >= 70) { data.cell.styles.textColor = [200, 150, 0]; data.cell.styles.fontStyle = "bold"; }
                    else { data.cell.styles.textColor = [200, 0, 0]; data.cell.styles.fontStyle = "bold"; }
                  }
                }
              },
              didDrawPage: () => drawBorder(doc),
          });
          
          grandY = (doc as any).lastAutoTable.finalY + 12;
        }
      });

      // After rendering grand summary, start a new page for the first day
      doc.addPage();
      drawBorder(doc);
    }

    dates.forEach((d, dateIdx) => {
      // Start each new date on a new page
      if (dateIdx > 0) {
        doc.addPage();
        drawBorder(doc);
      }

      // Draw the full header for this date!
      drawHeader(doc, d);
      y = 72;

      const dayLogs = logs.filter((l) => (l.date || reportDate) === d);

      const byRound: Record<number, ScanLog[]> = {};
      Object.keys(ROUND_TIMES).forEach((r) => {
        byRound[Number(r)] = [];
      });

      dayLogs.forEach((l) => {
        if (!byRound[l.round]) {
          byRound[l.round] = [];
        }
        byRound[l.round].push(l);
      });

      Object.keys(byRound)
        .map(Number)
        .sort((a, b) => a - b)
        .forEach((round) => {
          // Omit rounds with no data
          if (byRound[round].length === 0) {
            return;
          }

          if (y > height - 50) {
            doc.addPage();
            drawBorder(doc);
            y = 20;
          }

          const time = ROUND_TIMES[round];

          // Round Header
          doc.setFont("times", "bold");
          doc.setFontSize(12);
          doc.setTextColor(0, 0, 150);
          doc.text(
            `ROUND ${round} (${time?.start || "-"} - ${time?.end || "-"})`.toUpperCase(),
            14,
            y
          );

          y += 6;

          // ================= Rows =================
            const rows = byRound[round].map((l) => {
              const status = normalizeStatus(l.status);
              const timeStr = l.scan_time ? new Date(l.scan_time.replace(' ', 'T')).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }) : "-";
              
              return [
                timeStr.toUpperCase(),
                (l.guard_name || "-").toUpperCase(),
                (l.qr_name || "-").toUpperCase(),
                String(l.lat || "-").toUpperCase(),
                String(l.lon || "-").toUpperCase(),
                status.toUpperCase(),
              ];
            });

          // ================= Table =================
          autoTable(doc, {
            startY: y,
            head: [[
              "TIME",
              "GUARD",
              "QR POINT",
              "LATITUDE",
              "LONGITUDE",
              "STATUS",
            ]],
            body: rows,
            theme: "grid",
            styles: {
              font: "times",
              fontSize: 9,
              cellPadding: 3,
            },
            headStyles: {
              fillColor: [0, 70, 160],
              textColor: 255,
              fontStyle: "bold",
            },
            alternateRowStyles: {
              fillColor: [245, 248, 255],
            },
            didParseCell: (data) => {
              if (data.section === "body" && data.column.index === 5) {
                if (data.cell.raw === "SUCCESS") {
                  data.cell.styles.textColor = [0, 150, 0];
                  data.cell.styles.fontStyle = "bold";
                }
                if (data.cell.raw === "MISSED") {
                  data.cell.styles.textColor = [200, 0, 0];
                  data.cell.styles.fontStyle = "bold";
                }
                if (data.cell.raw === "PENDING") {
                  data.cell.styles.textColor = [200, 150, 0];
                  data.cell.styles.fontStyle = "bold";
                }
                if (data.cell.raw === "No Data") {
                  data.cell.styles.textColor = [255, 140, 0];
                  data.cell.styles.fontStyle = "bold";
                }
              }
            },
            didDrawPage: () => {
              drawBorder(doc);
            },
          });

          y = (doc as any).lastAutoTable.finalY + 12;
        });

      // ================= Daily Guard Summary (By Shift) =================
      const isTimeInShift = (time: string, start: string, end: string) => {
        if (!time || !start || !end) return false;
        const t = time.substring(0, 5);
        const s = start.substring(0, 5);
        const e = end.substring(0, 5);
        if (s <= e) return t >= s && t < e;
        return t >= s || t < e;
      };

      const shiftsToProcess = (shifts && shifts.length > 0) 
        ? shifts 
        : [{ shift_name: "ALL DAY", start_time: "00:00:00", end_time: "24:00:00" }]; // Fallback if no shifts

      shiftsToProcess.forEach(shift => {
        const shiftLogs = shiftsToProcess.length === 1 && shift.shift_name === "ALL DAY"
          ? dayLogs
          : dayLogs.filter(l => {
              const roundTime = ROUND_TIMES[l.round];
              return roundTime && isTimeInShift(roundTime.start, shift.start_time, shift.end_time);
            });

        if (shiftLogs.length === 0) return;

        const dailyGuardMap: Record<string, { scanned: number, missed: number }> = {};
        
        shiftLogs.forEach(r => {
          const status = normalizeStatus(r.status);
          if (status === 'SUCCESS' || status === 'MISSED') {
            const guardsList = (r.guard_name || 'Unknown').split(',').map(name => name.trim()).filter(Boolean);
            guardsList.forEach(g => {
              if (!dailyGuardMap[g]) dailyGuardMap[g] = { scanned: 0, missed: 0 };
              if (status === 'SUCCESS') dailyGuardMap[g].scanned++;
              else dailyGuardMap[g].missed++;
            });
          }
        });
        
        const dailySummaryRows = Object.entries(dailyGuardMap)
          .filter(([name, stats]) => name !== 'Unknown' || stats.scanned > 0 || stats.missed > 0)
          .sort(([, aStats], [, bStats]) => {
              const aTotal = aStats.scanned + aStats.missed;
              const bTotal = bStats.scanned + bStats.missed;
              const aPct = aTotal > 0 ? (aStats.scanned / aTotal) : 0;
              const bPct = bTotal > 0 ? (bStats.scanned / bTotal) : 0;
              if (bPct !== aPct) return bPct - aPct;
              return bStats.scanned - aStats.scanned;
          })
          .map(([name, stats]) => {
             const total = stats.scanned + stats.missed;
             const pct = total > 0 ? Math.round((stats.scanned / total) * 100) : 0;
             return [name.toUpperCase(), String(stats.scanned), String(stats.missed), String(total), `${pct}%`];
          });

        if (dailySummaryRows.length > 0) {
          if (y > height - 60) {
              doc.addPage();
              drawBorder(doc);
              y = 20;
          } else {
              y += 8;
          }

          doc.setFont("times", "bold");
          doc.setFontSize(12);
          doc.setTextColor(0, 0, 150);
          
          const shiftTitle = `DAILY PERFORMANCE SUMMARY - ${shift.shift_name} (${d})`;
          doc.text(shiftTitle.toUpperCase(), 14, y);
          y += 6;

          autoTable(doc, {
              startY: y,
              head: [["GUARD NAME", "SUCCESSFUL SCANS", "MISSED SCANS", "TOTAL ASSIGNED", "SUCCESS RATE"]],
              body: dailySummaryRows,
              theme: "grid",
              styles: { font: "times", fontSize: 10, cellPadding: 3 },
              headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: "bold" },
              alternateRowStyles: { fillColor: [245, 248, 255] },
              columnStyles: { 1: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' }, 4: { halign: 'center' } },
              didParseCell: (data) => {
                if (data.section === "body") {
                  if (data.column.index === 4) {
                    const pct = parseInt(String(data.cell.raw));
                    if (pct >= 90) { data.cell.styles.textColor = [0, 150, 0]; data.cell.styles.fontStyle = "bold"; }
                    else if (pct >= 70) { data.cell.styles.textColor = [200, 150, 0]; data.cell.styles.fontStyle = "bold"; }
                    else { data.cell.styles.textColor = [200, 0, 0]; data.cell.styles.fontStyle = "bold"; }
                  }
                }
              },
              didDrawPage: () => drawBorder(doc),
          });
          
          y = (doc as any).lastAutoTable.finalY + 12;
        }
      });

      if (dateIdx < dates.length - 1) {
        y += 4;
      }
    });


    // ================= Footer =================
    // ================= Footer =================
const pages = doc.getNumberOfPages();

for (let i = 1; i <= pages; i++) {

  doc.setPage(i);

  doc.setFont("times", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);

  // Page Number (Center)
  doc.text(
    `Page ${i} of ${pages} | KCET Security Rounds`,
    width / 2,
    height - 12,
    { align: "center" }
  );

  // ✅ Generated By (Bottom Left)
  doc.text(
    `Generated By : ${generatedBy}`,
    14,
    height - 12
  );
}



    // ================= Save =================
    doc.save(`Patrol_Report_${campusCode}_${reportDate}.pdf`);
  };


  return null;
};

export default PatrolReportPDF;
