import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { SecurityUser } from "@/app/types/securityUser";
import { Download, ChevronDown } from "lucide-react";
import { LOGO_BASE64 } from "../reports/logoBase64"; 

interface Props {
  users: SecurityUser[];
}

const UserPDFDownloader: React.FC<Props> = ({ users }) => {
  const [selectedRole, setSelectedRole] = useState("Guard");
  const [loading, setLoading] = useState(false);

  const drawBorder = (doc: jsPDF) => {
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(0, 0, 150);
    doc.setLineWidth(0.8);
    doc.rect(8, 8, w - 16, h - 16);
  };

    const handleDownload = async () => {
    setLoading(true);
    try {
      const filteredUsers = users.filter(
        (u) => (u.role || "").toUpperCase() === selectedRole.toUpperCase()
      );

      const doc = new jsPDF("portrait", "pt", "a4");
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 30;
      const generatedBy = localStorage.getItem("name") || localStorage.getItem("adminName") || "Admin";

      // Header
      doc.setDrawColor(0);
      doc.setLineWidth(2);
      doc.rect(15, 15, pageWidth - 30, pageHeight - 30);

      if (LOGO_BASE64) {
        try { doc.addImage(LOGO_BASE64, "PNG", pageWidth / 2 - 30, 25, 60, 60); } catch (e) {}
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(0);
      doc.text("SECURITY PERSONNEL MANAGEMENT", pageWidth / 2, 105, { align: "center" });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(80);
      doc.text("KCET Campus | Authorized Security Roster", pageWidth / 2, 120, { align: "center" });

      // Summary Box
      doc.setFillColor("#F8FAFC");
      doc.setDrawColor("#E2E8F0");
      doc.setLineWidth(1);
      doc.rect(margin, 135, pageWidth - (margin * 2), 35, "FD");

      doc.setFontSize(9);
      doc.setTextColor(40);
      doc.text(`Roster Type: ${selectedRole.toUpperCase()}`, margin + 10, 150);
      doc.text(`Generated By: ${generatedBy}`, margin + 10, 162);
      
      doc.setFont("helvetica", "bold");
      doc.text(`Total Personnel: ${filteredUsers.length}`, pageWidth - margin - 120, 156);

      const tableData = filteredUsers.map((u, i) => [
        `${i + 1}`,
        u.security_id || "-",
        u.security_name || "-",
        u.security_password || "-"
      ]);

      autoTable(doc, {
        startY: 180,
        margin: { top: 60, right: margin, bottom: 60, left: margin },
        head: [["S.No", "Employee ID", "Employee Name", "Password / PIN"]],
        body: tableData,
        theme: "grid",
        headStyles: { fillColor: "#4F46E5", textColor: "#FFFFFF", fontStyle: "bold", halign: "center", valign: "middle" },
        styles: { font: "helvetica", fontSize: 10, cellPadding: 8, valign: "middle" },
        columnStyles: {
          0: { cellWidth: 40, halign: "center" },
          1: { halign: "center", fontStyle: "bold" },
          3: { halign: "center", fontStyle: "italic" }
        },
        alternateRowStyles: { fillColor: "#F8FAFC" },
        didDrawPage: (data) => {
          doc.setDrawColor(0);
          doc.setLineWidth(2);
          doc.rect(15, 15, pageWidth - 30, pageHeight - 30);
          
          const str = "Page " + (doc as any).internal.getNumberOfPages();
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8);
          doc.setTextColor(150);
          doc.text(`Generated on: ${new Date().toLocaleString()}`, margin, pageHeight - 20);
          doc.text(str, pageWidth - margin - 40, pageHeight - 20);
        }
      });

      doc.save(`${selectedRole}_Roster.pdf`);
    } catch (error) {
      console.error("PDF generation failed", error);
      alert("Failed to generate PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <div className="relative">
        <select
          value={selectedRole}
          onChange={(e) => setSelectedRole(e.target.value)}
          className="input-field py-2 text-sm bg-white/95 cursor-pointer font-bold text-purple-950 pr-8 appearance-none shadow-sm h-[40px] rounded-xl"
        >
          <option value="Guard">Guards</option>
          <option value="Supervisor">Supervisors</option>
        </select>
        <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-purple-400 pointer-events-none" />
      </div>
      <button
        onClick={handleDownload}
        disabled={loading}
        className="btn-secondary flex items-center gap-2 bg-gradient-to-r from-purple-500 to-indigo-500 text-white hover:from-purple-600 hover:to-indigo-600 px-4 py-2 rounded-xl shadow font-semibold disabled:opacity-50"
      >
        <Download className="w-4 h-4" />
        {loading ? "Generating..." : "Download"}
      </button>
    </div>
  );
};

export default UserPDFDownloader;
