import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { SecurityUser } from "@/app/types/securityUser";
import { Download } from "lucide-react";
import { LOGO_BASE64 } from "../reports/logoBase64"; // Same logo as report download

interface Props {
  users: SecurityUser[];
}

const UserPDFDownloader: React.FC<Props> = ({ users }) => {
  const [selectedRole, setSelectedRole] = useState("Guard");
  const [loading, setLoading] = useState(false);

  // ================= Border =================
  const drawBorder = (doc: jsPDF) => {
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(0, 0, 180);
    doc.setLineWidth(0.8);
    doc.rect(8, 8, w - 16, h - 16);
  };

  const handleDownload = async () => {
    setLoading(true);
    try {
      const filteredUsers = users.filter(
        (u) => (u.role || "").toUpperCase() === selectedRole.toUpperCase()
      );

      const doc = new jsPDF();
      const width = doc.internal.pageSize.getWidth();
      const generatedBy = localStorage.getItem("name") || localStorage.getItem("adminName") || "Admin";
      
      drawBorder(doc);

      // ================= Header Drawer =================
      try {
        doc.addImage(LOGO_BASE64, "JPEG", 14, 12, 28, 28);
      } catch (e) {
        console.warn("Could not load logo to PDF", e);
      }

      doc.setTextColor(0, 0, 150);
      doc.setFont("times", "bold");
      doc.setFontSize(20);
      doc.text("SECURITY PERSONNEL MANAGEMENT", width / 2, 20, { align: "center" });

      doc.setFontSize(16);
      doc.text("KNOWLEDGE INSTITUTE OF TECHNOLOGY", width / 2, 30, {
        align: "center",
      });

      doc.setFont("times", "normal");
      doc.setFontSize(11);
      doc.text("KNOWLEDGE INSTITUTE OF TECHNOLOGY, SALEM", width / 2, 38, {
        align: "center",
      });

      // Role Title
      doc.setFont("times", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 150);
      doc.text(`${selectedRole.toUpperCase()} LIST`, width / 2, 50, {
        align: "center",
      });

      // ================= Table =================
      const tableData = filteredUsers.map((u) => [
        u.security_id || "-",
        u.security_name || "-",
        u.security_password || "-"
      ]);

      autoTable(doc, {
        startY: 55,
        head: [["Employee ID", "Employee Name", "Password / PIN"]],
        body: tableData,
        theme: "grid",
        headStyles: {
          fillColor: [0, 0, 150], 
          textColor: [255, 255, 255], 
          fontStyle: "bold",
          halign: "center",
        },
        bodyStyles: {
          textColor: [40, 40, 40],
          halign: "center",
        },
        alternateRowStyles: {
          fillColor: [245, 245, 250], 
        },
        styles: {
          font: "times",
          fontSize: 11,
          cellPadding: 4,
          lineColor: [200, 200, 200],
          lineWidth: 0.1,
        },
        didDrawPage: (data) => {
          // Keep border on every page
          drawBorder(doc);
        },
      });

      // ================= Footer (Generated By) =================
      // Put session ID (Generated By) and Date/Time exactly as requested below the table
      const finalY = (doc as any).lastAutoTable.finalY || 60;
      
      // If we are too close to the bottom, add a new page
      if (finalY > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        drawBorder(doc);
        doc.setFont("times", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40);
        doc.text(`GENERATED BY : ${generatedBy.toUpperCase()}`, 14, 25);
        doc.text(`GENERATED AT : ${new Date().toLocaleString().toUpperCase()}`, 14, 31);
      } else {
        doc.setFont("times", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40);
        doc.text(`GENERATED BY : ${generatedBy.toUpperCase()}`, 14, finalY + 15);
        doc.text(`GENERATED AT : ${new Date().toLocaleString().toUpperCase()}`, 14, finalY + 21);
      }

      doc.save(`${selectedRole}_Management_Report.pdf`);
    } catch (error) {
      console.error("PDF generation failed", error);
      alert("Failed to generate PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <select
        value={selectedRole}
        onChange={(e) => setSelectedRole(e.target.value)}
        className="px-4 py-2 rounded-xl border border-slate-200/60 bg-white/50 backdrop-blur-sm shadow-sm outline-none focus:border-purple-300 focus:ring-2 focus:ring-purple-200 transition-all font-medium text-slate-700"
      >
        <option value="Guard">Guards</option>
        <option value="Supervisor">Supervisors</option>
      </select>
      <button
        onClick={handleDownload}
        disabled={loading}
        className="btn-secondary flex items-center gap-2 bg-gradient-to-r from-purple-500 to-indigo-500 text-white hover:from-purple-600 hover:to-indigo-600 px-4 py-2 rounded-xl shadow font-semibold disabled:opacity-50"
      >
        <Download className="w-4 h-4" />
        {loading ? "Generating..." : "Download"}
      </button>
    </div>
  );
};

export default UserPDFDownloader;
