import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { SecurityUser } from "@/app/types/securityUser";
import { Download, ChevronDown } from "lucide-react";
import { LOGO_BASE64 } from "../reports/logoBase64"; 

interface Props {
  users: SecurityUser[];
}

const UserPDFDownloader: React.FC<Props> = ({ users }) => {
  const [selectedRole, setSelectedRole] = useState("Guard");
  const [loading, setLoading] = useState(false);

  const drawBorder = (doc: jsPDF) => {
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(0, 0, 150);
    doc.setLineWidth(0.8);
    doc.rect(8, 8, w - 16, h - 16);
  };

  const handleDownload = async () => {
    setLoading(true);
    try {
      const filteredUsers = users.filter(
        (u) => (u.role || "").toUpperCase() === selectedRole.toUpperCase()
      );

      const doc = new jsPDF();
      const width = doc.internal.pageSize.getWidth();
      const generatedBy = localStorage.getItem("name") || localStorage.getItem("adminName") || "Admin";
      
      drawBorder(doc);

      // ================= Header Drawer =================
      try {
        doc.addImage(LOGO_BASE64, "JPEG", 14, 12, 28, 28);
      } catch (e) {
        console.warn("Could not load logo to PDF", e);
      }

      doc.setTextColor(0, 0, 150);
      doc.setFont("times", "bold");
      doc.setFontSize(20);
      doc.text("SECURITY PERSONNEL MANAGEMENT", width / 2, 20, { align: "center" });

      doc.setFontSize(16);
      doc.text("KCET MAIN CAMPUS", width / 2, 30, { align: "center" });

      doc.setFont("times", "normal");
      doc.setFontSize(11);
      doc.text("KAMARAJ COLLEGE OF ENGINEERING AND TECHNOLOGY", width / 2, 38, { align: "center" });

      // ================= Meta Info (Top Left) =================
      const todayStr = new Date().toISOString().split('T')[0];
      doc.setFont("times", "bold");
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 150);
      doc.text(`DATE : ${todayStr}`, 14, 50);

      doc.setFont("times", "normal");
      doc.setFontSize(9);
      doc.setTextColor(40);
      doc.text(`GENERATED BY : ${generatedBy.toUpperCase()}`, 14, 57);
      doc.text(`GENERATED AT : ${new Date().toLocaleString().toUpperCase()}`, 14, 63);

      // Section Title
      doc.setFont("times", "bold");
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 150);
      doc.text(`${selectedRole.toUpperCase()} LIST`, 14, 73);

      // ================= Table =================
      const tableData = filteredUsers.map((u) => [
        u.security_id || "-",
        u.security_name || "-",
        u.security_password || "-"
      ]);

      const headStyles = {
        fillColor: [0, 0, 150] as [number, number, number], 
        textColor: [255, 255, 255] as [number, number, number], 
        fontStyle: "bold" as const,
        halign: "center" as const,
      };

      const baseStyles = {
        font: "times",
        cellPadding: 4,
        lineColor: [200, 200, 200] as [number, number, number],
        lineWidth: 0.1,
      };

      // If we have many users, split them into two side-by-side columns on the same page
      // Reduced threshold to 15 so that 18 rows (current count) perfectly splits into two columns on one page.
      const MAX_ROWS_PER_COL = 15;

      if (tableData.length <= MAX_ROWS_PER_COL) {
        // Single column
        autoTable(doc, {
          startY: 77,
          margin: { bottom: 15 },
          head: [["Employee ID", "Employee Name", "Password / PIN"]],
          body: tableData,
          theme: "grid",
          headStyles,
          bodyStyles: { textColor: [40, 40, 40], halign: "center" },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          styles: { ...baseStyles, fontSize: 10 },
          didDrawPage: () => drawBorder(doc),
        });
      } else {
        // Two columns side-by-side to fit on one page
        const mid = Math.ceil(tableData.length / 2);
        const leftData = tableData.slice(0, mid);
        const rightData = tableData.slice(mid);

        const colWidth = (width - 28 - 6) / 2; // 14 margin left, 14 margin right, 6 gap

        // Left Table
        autoTable(doc, {
          startY: 77,
          margin: { left: 14, right: 14 + colWidth + 6, bottom: 15 },
          head: [["ID", "Name", "Password"]],
          body: leftData,
          theme: "grid",
          headStyles,
          bodyStyles: { textColor: [40, 40, 40], halign: "center" },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          styles: { ...baseStyles, fontSize: 9, cellPadding: 3 },
          didDrawPage: () => drawBorder(doc),
        });

        // Right Table
        autoTable(doc, {
          startY: 77,
          margin: { left: 14 + colWidth + 6, right: 14, bottom: 15 },
          head: [["ID", "Name", "Password"]],
          body: rightData,
          theme: "grid",
          headStyles,
          bodyStyles: { textColor: [40, 40, 40], halign: "center" },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          styles: { ...baseStyles, fontSize: 9, cellPadding: 3 },
          // No need to drawBorder again on didDrawPage for the right table on the same page
        });
      }

      doc.save(`${selectedRole}_Management_Report.pdf`);
    } catch (error) {
      console.error("PDF generation failed", error);
      alert("Failed to generate PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <div className="relative">
        <select
          value={selectedRole}
          onChange={(e) => setSelectedRole(e.target.value)}
          className="input-field py-2 text-sm bg-white/95 cursor-pointer font-bold text-purple-950 pr-8 appearance-none shadow-sm h-[40px] rounded-xl"
        >
          <option value="Guard">Guards</option>
          <option value="Supervisor">Supervisors</option>
        </select>
        <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-purple-400 pointer-events-none" />
      </div>
      <button
        onClick={handleDownload}
        disabled={loading}
        className="btn-secondary flex items-center gap-2 bg-gradient-to-r from-purple-500 to-indigo-500 text-white hover:from-purple-600 hover:to-indigo-600 px-4 py-2 rounded-xl shadow font-semibold disabled:opacity-50"
      >
        <Download className="w-4 h-4" />
        {loading ? "Generating..." : "Download"}
      </button>
    </div>
  );
};

export default UserPDFDownloader;
