'use client'

import { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import {
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend,
  BarChart, Bar, XAxis, YAxis, CartesianGrid, LineChart, Line, Area, AreaChart,
} from 'recharts'
import { getPatrolReport, PatrolReportItem } from '../api/report'
import { getShifts } from '../api/shifts.api'
import { getQRCodes } from '../api/qr.api'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { useAuthGuard } from '@/app/services/auth.guard'

import { LOGO_BASE64 } from '../components/reports/logoBase64'

/* ================================================================
   TYPES
================================================================ */
type Campus = { campus_code: string; campus_name: string }

type DashboardStats = {
  total: number; completed: number; missed: number; pending: number; rate: number
  lastScan: string | null
  roundSummary: { round: string; completed: number; missed: number }[]
  shiftLeaderboards: {
    shiftName: string;
    totalExpectedScans: number;
    guards: { name: string; scanned: number; missed: number; total: number }[];
  }[]
  guardLeaderboard: { name: string; scanned: number; missed: number; total: number }[]
  coverageByPoint: { name: string; done: number; total: number }[]
  recentActivity: PatrolReportItem[]
}

/* ================================================================
   HELPERS
================================================================ */
function fmtTime(t: string | null) {
  if (!t) return '—'
  try { 
    const safeT = t.replace(' ', 'T')
    const d = new Date(safeT)
    return isNaN(d.getTime()) ? t : d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) 
  }
  catch { return t }
}

function exportDashboardPDF(
  statsData: DashboardStats,
  campus: string,
  campusName: string,
  date: string,
  adminName: string
) {
  const btn = document.getElementById('pdf-export-btn')
  if (btn) { btn.textContent = '⏳ Generating…'; btn.setAttribute('disabled', 'true') }

  try {
    const doc = new jsPDF()
    const w = doc.internal.pageSize.getWidth()
    const h = doc.internal.pageSize.getHeight()

    const drawBorder = () => {
      doc.setDrawColor(0, 0, 180)
      doc.setLineWidth(0.8)
      doc.rect(8, 8, w - 16, h - 16)
    }
    drawBorder()

    // ========== HEADER ==========
    try {
      doc.addImage(LOGO_BASE64, "JPEG", 14, 12, 28, 28);
    } catch (e) {
      console.warn("Could not load logo", e);
    }
    
    doc.setFont('times', 'bold')
    doc.setTextColor(0, 0, 150)
    doc.setFontSize(20)
    doc.text('Security Patrol Analytics Report', w / 2, 22, { align: 'center' })
    doc.setFontSize(14)
    doc.text(campusName.toUpperCase(), w / 2, 32, { align: 'center' })
    doc.setFont('times', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 150)
    doc.text(`Date : ${date}`, 14, 44)
    doc.setFont('times', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(40)
    doc.text(`Generated By : ${adminName}`, 14, 51)
    doc.text(`Generated At : ${new Date().toLocaleString()}`, 14, 57)

    let y = 68

    // ========== SUMMARY STATS ==========
    doc.setFont('times', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(0, 0, 150)
    doc.text('Summary Statistics', 14, y)
    y += 6

    autoTable(doc, {
      startY: y,
      head: [['Metric', 'Value']],
      body: [
        ['Total Effective Scans', String(statsData.total)],
        ['Completed', `${statsData.completed} (${statsData.rate}%)`],
        ['Missed', String(statsData.missed)],
        ['Pending (Not Due)', String(statsData.pending)],
        ['Last Scan Time', statsData.lastScan ? new Date(statsData.lastScan).toLocaleTimeString('en-IN') : '—'],
      ],
      theme: 'grid',
      styles: { font: 'times', fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 255] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 1) {
          if (data.row.index === 1) data.cell.styles.textColor = [0, 150, 0]
          if (data.row.index === 2) data.cell.styles.textColor = [200, 0, 0]
          if (data.row.index === 3) data.cell.styles.textColor = [150, 120, 0]
        }
      },
      didDrawPage: () => drawBorder(),
    })
    y = (doc as any).lastAutoTable.finalY + 12

    // ========== ROUND-BY-ROUND ==========
    if (statsData.roundSummary.length > 0) {
      if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
      doc.setFont('times', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(0, 0, 150)
      doc.text('Round-by-Round Breakdown', 14, y)
      y += 6

      autoTable(doc, {
        startY: y,
        head: [['Round', 'Completed', 'Missed', 'Total', 'Rate']],
        body: statsData.roundSummary.map(r => [
          r.round,
          String(r.completed),
          String(r.missed),
          String(r.completed + r.missed),
          `${r.completed + r.missed > 0 ? Math.round((r.completed / (r.completed + r.missed)) * 100) : 0}%`,
        ]),
        theme: 'grid',
        styles: { font: 'times', fontSize: 9, cellPadding: 2.5, halign: 'center' },
        headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        didParseCell: (data) => {
          if (data.section === 'body') {
            if (data.column.index === 1) data.cell.styles.textColor = [0, 150, 0]
            if (data.column.index === 2 && Number(data.cell.raw) > 0) data.cell.styles.textColor = [200, 0, 0]
          }
        },
        didDrawPage: () => drawBorder(),
      })
      y = (doc as any).lastAutoTable.finalY + 12
    }

    // ========== SCAN POINT COVERAGE ==========
    if (statsData.coverageByPoint.length > 0) {
      if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
      doc.setFont('times', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(0, 0, 150)
      doc.text('Scan Point Coverage', 14, y)
      y += 6

      autoTable(doc, {
        startY: y,
        head: [['Scan Point', 'Completed', 'Missed', 'Coverage %']],
        body: statsData.coverageByPoint.map(p => {
          const pct = p.total ? Math.round((p.done / p.total) * 100) : 0
          return [p.name, String(p.done), String(p.total - p.done), `${pct}%`]
        }),
        theme: 'grid',
        styles: { font: 'times', fontSize: 9, cellPadding: 2.5 },
        headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        columnStyles: { 1: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 3) {
            const pct = parseInt(String(data.cell.raw))
            if (pct >= 80) data.cell.styles.textColor = [0, 150, 0]
            else if (pct >= 50) data.cell.styles.textColor = [200, 150, 0]
            else data.cell.styles.textColor = [200, 0, 0]
            data.cell.styles.fontStyle = 'bold'
          }
        },
        didDrawPage: () => drawBorder(),
      })
      y = (doc as any).lastAutoTable.finalY + 12
    }

    // ========== GUARD LEADERBOARD ==========
    if (statsData.guardLeaderboard.length > 0) {
      if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
      doc.setFont('times', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(0, 0, 150)
      doc.text('Guard Performance', 14, y)
      y += 6

      autoTable(doc, {
        startY: y,
        head: [['Rank', 'Guard Name', 'Scanned', 'Missed', 'Total', 'Rate']],
        body: statsData.guardLeaderboard.map((g, i) => [
          `#${i + 1}`,
          g.name,
          String(g.scanned),
          String(g.missed),
          String(g.total),
          `${g.total ? Math.round((g.scanned / g.total) * 100) : 0}%`,
        ]),
        theme: 'grid',
        styles: { font: 'times', fontSize: 9, cellPadding: 2.5 },
        headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        columnStyles: { 0: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' }, 4: { halign: 'center' }, 5: { halign: 'center' } },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 5) {
            const pct = parseInt(String(data.cell.raw))
            if (pct >= 90) data.cell.styles.textColor = [0, 150, 0]
            else if (pct >= 70) data.cell.styles.textColor = [200, 150, 0]
            else data.cell.styles.textColor = [200, 0, 0]
            data.cell.styles.fontStyle = 'bold'
          }
        },
        didDrawPage: () => drawBorder(),
      })
      y = (doc as any).lastAutoTable.finalY + 12
    }

    // ========== RECENT ACTIVITY ==========
    if (statsData.recentActivity.length > 0) {
      if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
      doc.setFont('times', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(0, 0, 150)
      doc.text('Recent Scan Activity (Last 10)', 14, y)
      y += 6

      autoTable(doc, {
        startY: y,
        head: [['Time', 'Guard', 'QR Point', 'Round', 'Status']],
        body: statsData.recentActivity.map(r => [
          r.scan_time ? new Date(r.scan_time).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—',
          r.guard_name || '—',
          r.qr_name,
          `Round ${r.round}`,
          r.status,
        ]),
        theme: 'grid',
        styles: { font: 'times', fontSize: 9, cellPadding: 2.5 },
        headStyles: { fillColor: [0, 70, 160], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 4) {
            if (data.cell.raw === 'SUCCESS') { data.cell.styles.textColor = [0, 150, 0]; data.cell.styles.fontStyle = 'bold' }
            if (data.cell.raw === 'MISSED') { data.cell.styles.textColor = [200, 0, 0]; data.cell.styles.fontStyle = 'bold' }
          }
        },
        didDrawPage: () => drawBorder(),
      })
    }

    // ========== FOOTER ON ALL PAGES ==========
    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFont('times', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(120)
      doc.text(`Page ${i} of ${pages} | KCET Security Rounds`, w / 2, h - 12, { align: 'center' })
    }

    doc.save(`Analytics_Report_${campus}_${date}.pdf`)
  } catch (err) {
    console.error('PDF export error:', err)
    alert('Failed to generate PDF. Please try again.')
  } finally {
    if (btn) { btn.textContent = '📊 Export PDF'; btn.removeAttribute('disabled') }
  }
}

/* ================================================================
   STAT CARD
================================================================ */
function StatCard({ label, value, sub, color, bg, icon }: {
  label: string; value: string | number; sub?: string
  color: string; bg: string; icon?: string
}) {
  return (
    <motion.div 
      whileHover={{ y: -5, scale: 1.02 }}
      className="glass-panel rounded-3xl p-5 relative overflow-hidden group hover:shadow-lg transition-all duration-300"
    >
      <div className={`absolute left-0 top-0 h-full w-1.5 ${bg}`} />
      <div className="pl-3 relative z-10">
        <p className="text-xs font-semibold uppercase tracking-widest text-slate-500">{label}</p>
        <p className={`mt-1.5 text-2xl font-bold ${color}`}>{value}</p>
        {sub && <p className="mt-0.5 text-xs font-medium text-slate-400">{sub}</p>}
      </div>
      {icon && <div className="absolute right-[-10%] top-[-10%] opacity-[0.03] text-8xl group-hover:scale-110 transition-transform duration-500 pointer-events-none select-none">{icon}</div>}
    </motion.div>
  )
}

/* ================================================================
   PROGRESS BAR (for scan point coverage)
================================================================ */
function CoverageBar({ name, done, total }: { name: string; done: number; total: number }) {
  const pct = total ? Math.round((done / total) * 100) : 0
  const color = pct === 100 ? 'bg-amber-500' : pct >= 50 ? 'bg-amber-400' : 'bg-rose-500'
  return (
    <div className="mb-3">
      <div className="flex items-center justify-between mb-1">
        <span className="text-xs font-medium text-slate-600 truncate max-w-[180px]">{name}</span>
        <span className={`text-xs font-bold ${pct === 100 ? 'text-amber-600' : pct >= 50 ? 'text-amber-600' : 'text-rose-600'}`}>{pct}%</span>
      </div>
      <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
        <div className={`h-full rounded-full ${color} transition-all duration-700`} style={{ width: `${pct}%` }} />
      </div>
    </div>
  )
}

/* ================================================================
   GUARD LEADERBOARD ROW
================================================================ */
function LeaderRow({ rank, name, scanned, missed, total }: {
  rank: number; name: string; scanned: number; missed: number; total: number
}) {
  const pct = total ? Math.round((scanned / total) * 100) : 0
  const medal = rank === 1 ? '🥇' : rank === 2 ? '🥈' : rank === 3 ? '🥉' : `#${rank}`
  const color = pct >= 90 ? 'text-amber-600 bg-amber-50' : pct >= 70 ? 'text-amber-600 bg-amber-50' : 'text-rose-600 bg-rose-50'
  return (
    <div className="flex items-center gap-3 py-2.5 border-b border-slate-50 last:border-0">
      <div className="w-8 text-center text-lg">{medal}</div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center justify-between mb-1">
          <span className="text-sm font-semibold text-slate-700 truncate">{name}</span>
          <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${color}`}>{pct}%</span>
        </div>
        <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
          <div
            className={`h-full rounded-full transition-all duration-700 ${pct >= 90 ? 'bg-amber-500' : pct >= 70 ? 'bg-amber-400' : 'bg-rose-500'}`}
            style={{ width: `${pct}%` }}
          />
        </div>
        <p className="text-xs text-slate-400 mt-0.5">{scanned} scanned · {missed} missed</p>
      </div>
    </div>
  )
}

export default function DashboardPage() {
  const router = useRouter()
  const { authorized } = useAuthGuard({ allowedRoles: ['ADMIN'] });
  // Fix today to use local time properly instead of UTC
  const today = useMemo(() => {
    const d = new Date();
    const offset = d.getTimezoneOffset() * 60000;
    return new Date(d.getTime() - offset).toISOString().slice(0, 10);
  }, [])
  const dashboardContentRef = useRef<HTMLDivElement>(null)

  const [adminName, setAdminName]             = useState('')
  const FIXED_CAMPUS                          = 'KCET01'
  const [selectedDate, setSelectedDate]       = useState(today)
  const [report, setReport]                   = useState<PatrolReportItem[]>([])
  const [shifts, setShifts]                   = useState<any[]>([])
  const [qrs, setQrs]                         = useState<any[]>([])
  const [lastUpdated, setLastUpdated]         = useState('')

  /* auth check */
  useEffect(() => {
    if (authorized) {
      const name = localStorage.getItem('adminName') || ''
      setAdminName(name)
    }
  }, [authorized])

  const fetchReportAndShifts = useCallback(() => {
    if (!authorized || !selectedDate) return
    setLoading(true)
    Promise.all([
      getPatrolReport(FIXED_CAMPUS, selectedDate),
      getShifts(),
      getQRCodes()
    ])
      .then(([reportData, shiftsData, qrsData]) => {
        setReport(reportData)
        setShifts(shiftsData)
        setQrs(qrsData)
        setLastUpdated(new Date().toLocaleTimeString())
      })
      .catch(() => { setReport([]); setShifts([]); setQrs([]) })
      .finally(() => setLoading(false))
  }, [selectedDate, authorized])

  /* auto-fetch when campus/date changes */
  useEffect(() => {
    fetchReportAndShifts()
  }, [fetchReportAndShifts])

  /* ================================================================
     COMPUTED STATS (time-aware)
  ================================================================ */
  const stats = useMemo(() => {
    const empty = {
      total: 0, completed: 0, missed: 0, pending: 0, rate: 0, lastScan: null as string | null,
      pie: [], roundSummary: [], shiftLeaderboards: [], guardLeaderboard: [], coverageByPoint: [],
      hourlyActivity: [], recentActivity: [], isPartialDay: false, nothingScannedToday: false, timeline: [] as any[]
    }
    if (!report.length) return empty

    const isToday = selectedDate === today

    const ROUND_TIMES = [
      "00:00","02:00","04:00","06:00",
      "08:00","10:00","12:00","14:00",
      "16:00","18:00","20:00","22:00"
    ];

    // Compute expected target based on historical QRs
    const selectedDateEnd = new Date(`${selectedDate}T23:59:59.999`);
    const activeQRsOnDate = qrs.filter((q: any) => {
      if (q.campus_code && q.campus_code !== FIXED_CAMPUS) return false;
      const createdDate = new Date(q.created_at);
      return createdDate <= selectedDateEnd;
    });
    // Fallback to 1 if no QRs found to avoid divide by zero, though UI handles 0
    const targetScansPerRound = activeQRsOnDate.length;

    let dueRoundsCount = ROUND_TIMES.length;
    if (isToday) {
      const now = new Date();
      const currentHour = now.getHours();
      const currentMinute = now.getMinutes();
      dueRoundsCount = 0;
      for (let i = 0; i < ROUND_TIMES.length; i++) {
        const h = parseInt(ROUND_TIMES[i].split(':')[0]);
        // A round is considered "due" (its window has closed) if we are past +1h30m from start
        if (currentHour > h + 1 || (currentHour === h + 1 && currentMinute >= 30)) {
          dueRoundsCount = i + 1;
        } else {
          break;
        }
      }
    }

    const scannedRounds = report.filter(r => r.scan_time !== null).map(r => r.round)
    const maxScannedRound = scannedRounds.length ? Math.max(...scannedRounds) : 0
    const nothingScannedToday = isToday && maxScannedRound === 0
    const isPartialDay = isToday && dueRoundsCount < ROUND_TIMES.length

    const effective = isToday
      ? report.filter(r => r.round <= dueRoundsCount || r.status === 'SUCCESS')
      : report
    const pending = report.length - effective.length

    /* ── base stats ── */
    const completed = effective.filter(r => r.status === 'SUCCESS').length
    const missed    = nothingScannedToday ? 0 : effective.filter(r => r.status === 'MISSED').length
    const total     = completed + missed
    const rate      = total ? Math.round((completed / total) * 100) : 0

    /* ── last scan time ── */
    const scanTimes = effective.filter(r => r.scan_time).map(r => r.scan_time as string).sort()
    const lastScan  = scanTimes.length ? scanTimes[scanTimes.length - 1] : null

    /* ── pie ── */
    const pie = [
      { name: 'Completed', value: completed, color: '#6366f1' },
      { name: 'Missed',    value: missed,    color: '#f43f5e' },
      ...(pending > 0 ? [{ name: 'Not Due Yet', value: pending, color: '#94a3b8' }] : []),
    ]

    /* ── rounds summary ── */
    const roundNums = [...new Set(effective.map(r => r.round))].sort((a, b) => a - b)
    const roundSummary = nothingScannedToday ? [] : roundNums.map(rnd => {
      const items = effective.filter(r => r.round === rnd)
      return {
        round: `R${rnd}`,
        completed: items.filter(i => i.status === 'SUCCESS').length,
        missed:    items.filter(i => i.status !== 'SUCCESS').length,
      }
    })

    /* ── shift leaderboards ── */
    const isTimeInShift = (time: string, start: string, end: string) => {
      if (!time || !start || !end) return false;
      const t = time.substring(0, 5);
      const s = start.substring(0, 5);
      const e = end.substring(0, 5);
      if (s <= e) return t >= s && t < e;
      return t >= s || t < e;
    };

    const shiftLeaderboards = shifts.map(shift => {
      // Find all report items (PENDING, MISSED, SUCCESS) for this shift
      // using ROUND_TIMES mapping
      const shiftItems = report.filter(r => {
        const roundTime = ROUND_TIMES[r.round - 1];
        return isTimeInShift(roundTime, shift.start_time, shift.end_time);
      });

      const totalExpectedScans = shiftItems.length;

      // Calculate guard performance for this shift using only effective scans
      const guardMap: Record<string, { scanned: number; missed: number }> = {};
      shiftItems.forEach(r => {
        // Only count effective scans for the leaderboard stats
        const isEffective = isToday ? (r.round <= dueRoundsCount || r.status === 'SUCCESS') : true;
        if (!isEffective) return;

        if (r.status === 'SUCCESS' || (!nothingScannedToday && r.status === 'MISSED')) {
          const guardsList = (r.guard_name || 'Unknown').split(',').map(name => name.trim()).filter(Boolean);
          guardsList.forEach(g => {
            if (!guardMap[g]) guardMap[g] = { scanned: 0, missed: 0 };
            if (r.status === 'SUCCESS') guardMap[g].scanned++;
            else guardMap[g].missed++;
          });
        }
      });

      const guards = Object.entries(guardMap)
        .filter(([n, d]) => n !== 'Unknown' || d.scanned > 0)
        .map(([name, d]) => ({ name, ...d, total: d.scanned + d.missed }))
        .sort((a, b) => b.scanned / (b.total || 1) - a.scanned / (a.total || 1));

      return {
        shiftName: shift.shift_name,
        totalExpectedScans,
        guards
      };
    });

    /* ── overall guard leaderboard (for charts) ── */
    const overallGuardMap: Record<string, { scanned: number; missed: number }> = {}
    effective.forEach(r => {
      if (r.status === 'SUCCESS' || (!nothingScannedToday && r.status === 'MISSED')) {
        const guardsList = (r.guard_name || 'Unknown').split(',').map(name => name.trim()).filter(Boolean);
        guardsList.forEach(g => {
          if (!overallGuardMap[g]) overallGuardMap[g] = { scanned: 0, missed: 0 };
          if (r.status === 'SUCCESS') overallGuardMap[g].scanned++;
          else overallGuardMap[g].missed++;
        });
      }
    })
    const guardLeaderboard = Object.entries(overallGuardMap)
      .filter(([n, d]) => n !== 'Unknown' || d.scanned > 0)
      .map(([name, d]) => ({ name, ...d, total: d.scanned + d.missed }))
      .sort((a, b) => b.scanned / (b.total || 1) - a.scanned / (a.total || 1))

    /* ── scan point coverage (progress bars) ── */
    const pointMap: Record<string, { done: number; total: number }> = {}
    effective.forEach(r => {
      if (!pointMap[r.qr_name]) pointMap[r.qr_name] = { done: 0, total: 0 }
      pointMap[r.qr_name].total++
      if (r.status === 'SUCCESS') pointMap[r.qr_name].done++
    })
    const coverageByPoint = Object.entries(pointMap)
      .map(([name, v]) => ({ name, ...v }))
      .sort((a, b) => (a.done / a.total) - (b.done / b.total))  // worst first

    /* ── hourly activity (group by round start hour, not raw scan time) ── */
    const hourMap: Record<number, number> = {}
    effective
      .filter(r => r.scan_time && r.status === 'SUCCESS')
      .forEach(r => {
        // Use the round's start hour instead of raw scan_time hour
        const roundIdx = r.round - 1
        if (roundIdx >= 0 && roundIdx < ROUND_TIMES.length) {
          const h = parseInt(ROUND_TIMES[roundIdx].split(':')[0])
          hourMap[h] = (hourMap[h] || 0) + 1
        } else {
          const h = new Date(r.scan_time!).getHours()
          hourMap[h] = (hourMap[h] || 0) + 1
        }
      })
    const hourlyActivity = Array.from({ length: 24 }, (_, h) => ({
      hour: `${String(h).padStart(2, '0')}:00`,
      scans: hourMap[h] || 0,
    })).filter(h => h.scans > 0 || (Object.keys(hourMap).length === 0))

    /* ── recent activity feed (last 10 successful scans) ── */
    const recentActivity = effective
      .filter(r => r.status === 'SUCCESS' && r.scan_time)
      .sort((a, b) => (b.scan_time || '').localeCompare(a.scan_time || ''))
      .slice(0, 10)

    /* ── timeline cards ── */
    const timeline = ROUND_TIMES.map((time, idx) => {
      const roundNo = idx + 1;
      const h = parseInt(time.split(':')[0]);
      
      let status: 'COMPLETED' | 'PARTIAL' | 'MISSED' | 'ACTIVE' | 'PENDING' = 'PENDING';
      let isActive = false;
      
      const items = report.filter(r => r.round === roundNo);
      const successCount = items.filter(r => r.status === 'SUCCESS').length;
      
      // We expect 'targetScansPerRound' scans for a fully completed round
      const isSuccess = successCount >= targetScansPerRound && targetScansPerRound > 0;
      const isPartial = successCount > 0 && successCount < targetScansPerRound;
      
      if (isToday) {
        const now = new Date();
        const currentMins = now.getHours() * 60 + now.getMinutes();
        const startMins = h * 60 + 45; // opens at +45m
        const endMins = h * 60 + 90;   // closes at +1h30m
        
        isActive = currentMins >= startMins && currentMins < endMins;
        const isPast = currentMins >= endMins;
        
        if (isSuccess) status = 'COMPLETED';
        else if (isPartial) status = 'PARTIAL';
        else if (isActive) status = 'ACTIVE';
        else if (isPast) status = 'MISSED';
        else status = 'PENDING';
      } else {
        // Past day
        if (isSuccess) status = 'COMPLETED';
        else if (isPartial) status = 'PARTIAL';
        else status = 'MISSED';
      }
      
      return {
        roundNo,
        timeLabel: `${String(h).padStart(2, '0')}:00 - ${String(h + 2).padStart(2, '0')}:00`,
        status
      };
    });

    return {
      total, completed, missed, pending, rate, lastScan, pie, roundSummary,
      shiftLeaderboards, guardLeaderboard, coverageByPoint, hourlyActivity, recentActivity,
      isPartialDay, nothingScannedToday, timeline
    }
  }, [report, selectedDate, today])

  const selectedCampusName = "KCET Main Campus"

  if (!authorized) {
    return <div className="p-6 text-white min-h-screen bg-[#07071f] flex items-center justify-center">Checking access...</div>
  }

  return (
    <div className="min-h-screen relative font-sans text-slate-900">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 relative z-10"
      >

        {/* ── HEADER ── */}
        <div className="mb-6 flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-slate-900">Analytics Dashboard</h1>
            <p className="mt-1 text-slate-500 text-sm">
              <span className="font-medium text-purple-600">{selectedCampusName}</span>
              {' · '}
              Patrol performance overview
              {lastUpdated && <span className="ml-2 text-amber-600 font-medium">· Updated {lastUpdated}</span>}
            </p>
          </div>
          <div className="flex items-center gap-2 text-sm text-slate-500">
            <div className="w-2 h-2 rounded-full bg-amber-500" />
            {adminName}
          </div>
        </div>

        {/* ── CONTROLS BAR ── */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glass-panel rounded-3xl p-5 mb-6"
        >
          <div className="flex flex-wrap items-end gap-4">



            <div className="flex-1 min-w-[140px]">
              <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Date</label>
              <input
                type="date" value={selectedDate}
                onChange={e => setSelectedDate(e.target.value)}
                className="w-full mt-2 pl-3 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
            </div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={fetchReportAndShifts} disabled={loading}
              className="bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white font-semibold px-5 py-2.5 rounded-lg flex items-center gap-2 text-sm transition-colors"
            >
              {loading
                ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />Loading…</>
                : '📊 Load'}
            </motion.button>



            {/* Export Analytics PDF */}
            {report.length > 0 && (
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                id="pdf-export-btn"
                onClick={() => exportDashboardPDF(stats, FIXED_CAMPUS, selectedCampusName, selectedDate, adminName)}
                className="border border-slate-200 bg-white hover:bg-slate-50 text-slate-600 font-semibold px-4 py-2.5 rounded-lg flex items-center gap-2 text-sm transition-colors"
              >
                📊 Export PDF
              </motion.button>
            )}

            {/* Go to full report */}
            {report.length > 0 && (
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => router.push('/report-download')}
                className="border border-purple-200 bg-purple-50 hover:bg-purple-100 text-purple-700 font-semibold px-4 py-2.5 rounded-lg flex items-center gap-2 text-sm transition-colors"
              >
                📄 Full Report
              </motion.button>
            )}
          </div>
        </motion.div>

        {/* ── DASHBOARD CONTENT (captured for PDF) ── */}
        <div ref={dashboardContentRef}>

        {/* ── STAT CARDS ── */}
        <div className="grid grid-cols-2 xl:grid-cols-5 gap-4 mb-6">
          <StatCard label="Effective Scans"  value={stats.total}           sub="Rounds due so far"  color="text-purple-600"  bg="bg-purple-500"  icon="📋" />
          <StatCard label="Completed"        value={stats.completed}       sub={`${stats.rate}% rate`} color="text-amber-600" bg="bg-amber-500" icon="✅" />
          <StatCard label="Missed"           value={stats.missed}          sub="Truly skipped"      color="text-rose-600"    bg="bg-rose-500"    icon="⚠️" />
          <StatCard label="Not Due Yet"      value={stats.pending ?? 0}    sub="Future rounds"      color="text-slate-500"   bg="bg-slate-400"   icon="🕐" />
          <StatCard
            label="Last Scan"
            value={stats.lastScan ? fmtTime(stats.lastScan) : '—'}
            sub="Most recent activity"
            color="text-violet-600" bg="bg-violet-500" icon="🔍"
          />
        </div>

        {/* ── DAY PROGRESS BAR ── */}
        {report.length > 0 && (
          <div className="glass-panel rounded-3xl p-6 mb-6">
            <div className="flex items-center justify-between mb-3">
              <div>
                <h2 className="text-sm font-semibold text-slate-700">Day Completion Progress</h2>
                <p className="text-xs text-slate-400">
                  {stats.completed} of {stats.total + (stats.pending ?? 0)} total expected scans completed
                </p>
              </div>
              <span className={`text-2xl font-extrabold ${stats.rate >= 90 ? 'text-amber-600' : stats.rate >= 60 ? 'text-amber-500' : 'text-rose-600'}`}>
                {stats.rate}%
              </span>
            </div>
            <div className="h-4 bg-slate-100 rounded-full overflow-hidden flex">
              {/* completed */}
              <div
                className="h-full bg-purple-500 transition-all duration-700 flex items-center justify-center"
                style={{ width: `${(stats.completed / (report.length || 1)) * 100}%` }}
              />
              {/* missed */}
              <div
                className="h-full bg-rose-400 transition-all duration-700"
                style={{ width: `${(stats.missed / (report.length || 1)) * 100}%` }}
              />
              {/* pending */}
              <div
                className="h-full bg-slate-200 transition-all duration-700"
                style={{ width: `${((stats.pending ?? 0) / (report.length || 1)) * 100}%` }}
              />
            </div>
            <div className="flex items-center gap-5 mt-2 text-xs text-slate-400">
              <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-purple-500 inline-block" />Completed</span>
              <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-rose-400 inline-block" />Missed</span>
              <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-slate-200 inline-block" />Not due yet</span>
            </div>
          </div>
        )}

        {/* ── ROUND TIMELINE CARDS ── */}
        {report.length > 0 && (
          <div className="mb-6">
            <h2 className="text-xl font-bold text-slate-800 tracking-tight mb-4 flex items-center gap-2">
              ⏱️ Daily Patrol Timeline
              <span className="text-sm font-normal text-slate-500 bg-slate-100 px-3 py-1 rounded-full">12-Round Daily Cycle</span>
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {stats.timeline?.map((item: any) => {
                let badge = null;
                if (item.status === 'COMPLETED') {
                  badge = <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-emerald-50 text-emerald-700 text-xs font-bold border border-emerald-200">🟢 Verified</span>;
                } else if (item.status === 'PARTIAL') {
                  badge = <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-blue-50 text-blue-700 text-xs font-bold border border-blue-200">🔵 Partial</span>;
                } else if (item.status === 'ACTIVE') {
                  badge = <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-amber-50 text-amber-700 text-xs font-bold border border-amber-200"><span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>🟡 Active Window</span>;
                } else if (item.status === 'MISSED') {
                  badge = <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-rose-50 text-rose-700 text-xs font-bold border border-rose-200">🔴 Missed</span>;
                } else {
                  badge = <span className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-slate-50 text-slate-500 text-xs font-bold border border-slate-200">⚪ Upcoming</span>;
                }

                return (
                  <div key={item.roundNo} className={`p-4 rounded-2xl border transition-all ${item.status === 'ACTIVE' ? 'bg-amber-50/50 border-amber-200 shadow-md ring-1 ring-amber-200' : 'bg-white border-slate-200 shadow-sm'}`}>
                    <div className="flex justify-between items-start mb-2">
                      <span className="text-sm font-bold text-slate-700">Round {item.roundNo}</span>
                      {badge}
                    </div>
                    <p className="text-xs text-slate-500 font-medium">{item.timeLabel}</p>
                    {(item.status === 'COMPLETED' || item.status === 'PARTIAL' || item.status === 'MISSED') && (
                      <p className={`text-xs mt-2 font-semibold ${item.status === 'COMPLETED' ? 'text-emerald-600' : item.status === 'PARTIAL' ? 'text-blue-600' : 'text-rose-600'}`}>
                        {item.successCount} out of {item.targetScans} Scanned
                      </p>
                    )}
                    {item.status === 'ACTIVE' && (
                      <p className="text-[10px] text-amber-600 mt-2 font-semibold uppercase tracking-wider">Accepting Scans...</p>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ── BANNERS ── */}
        {stats.nothingScannedToday && report.length > 0 && (
          <div className="mb-6 flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4">
            <span className="text-2xl">⏳</span>
            <div>
              <p className="font-semibold text-amber-800">Patrol not started yet today</p>
              <p className="text-sm text-amber-600">{report.length} rounds scheduled — no scans recorded yet. 0 marked as missed.</p>
            </div>
          </div>
        )}
        {stats.isPartialDay && (
          <div className="mb-6 flex items-center gap-4 rounded-2xl border border-purple-200 bg-purple-50/80 backdrop-blur-md px-6 py-5 shadow-sm transition-all hover:shadow-md">
            <div className="relative flex h-4 w-4 shrink-0">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-4 w-4 bg-purple-500 border-2 border-purple-200"></span>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <p className="font-bold text-purple-900 text-base tracking-tight">Active Patrol in Progress</p>
                <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold uppercase tracking-wider">Live System Health: Online</span>
              </div>
              <p className="text-sm text-purple-700/80 mt-0.5 font-medium">
                Live monitoring rounds due so far. <strong className="text-purple-900">{stats.pending ?? 0}</strong> future rounds excluded from missed count.
              </p>
            </div>
          </div>
        )}

        {/* ── CHARTS ── */}
        {report.length > 0 && !stats.nothingScannedToday ? (
          <>
            {/* ROW 1: Pie + Round-by-Round bar */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
              {/* Pie */}
              <div className="glass-panel rounded-3xl p-6 flex flex-col justify-between">
                <div>
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">Completion Overview</h2>
                  <p className="text-xs text-slate-400 mb-4">Completed · Missed · Not Due</p>
                </div>
                <ResponsiveContainer width="100%" height={240}>
                  <PieChart>
                    <Pie data={stats.pie} cx="50%" cy="50%" innerRadius={65} outerRadius={105} paddingAngle={4} dataKey="value">
                      {stats.pie.map((e, i) => <Cell key={i} fill={e.color} stroke="transparent" />)}
                    </Pie>
                    <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12, border: 'none', boxShadow: '0 4px 16px rgba(0,0,0,.1)' }} />
                    <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Round bar */}
              <div className="glass-panel rounded-3xl p-6">
                <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">Round-by-Round</h2>
                <p className="text-xs text-slate-400 mb-4">Completed vs Missed per patrol round</p>
                <ResponsiveContainer width="100%" height={240}>
                  <BarChart data={stats.roundSummary} barSize={10}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
                    <XAxis dataKey="round" tick={{ fill: '#94a3b8', fontSize: 10 }} axisLine={false} tickLine={false} />
                    <YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12, border: 'none', boxShadow: '0 4px 16px rgba(0,0,0,.1)' }} />
                    <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
                    <Bar dataKey="completed" fill="#06b6d4" radius={[4, 4, 0, 0]} name="Completed" />
                    <Bar dataKey="missed"    fill="#f43f5e" radius={[4, 4, 0, 0]} name="Missed" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* ROW 1.5: Guard Leaderboard by Shift */}
            {stats.shiftLeaderboards.length > 0 && (
              <div className="mb-6">
                <div className="flex items-center gap-3 mb-4 px-2">
                  <h2 className="text-xl font-bold text-slate-800 tracking-tight">🏆 Guard Leaderboard by Shift</h2>
                  <span className="text-sm text-slate-500 font-medium bg-slate-100 px-3 py-1 rounded-full">Scans Expected & Performance</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {stats.shiftLeaderboards.map(shift => (
                    <div key={shift.shiftName} className="glass-panel rounded-3xl p-6 flex flex-col h-[320px]">
                      <div className="flex justify-between items-start mb-1">
                        <h2 className="text-sm font-bold text-purple-700 uppercase tracking-widest">{shift.shiftName}</h2>
                        <span className="text-xs font-bold bg-purple-50 text-purple-600 px-2.5 py-1 rounded-lg">
                          {shift.totalExpectedScans} Scans
                        </span>
                      </div>
                      <p className="text-xs text-slate-400 mb-4">Ranked by completion rate</p>
                      <div className="overflow-y-auto flex-1 pr-1">
                        {shift.guards.length > 0
                          ? shift.guards.map((g, i) => (
                            <LeaderRow key={g.name} rank={i + 1} name={g.name}
                              scanned={g.scanned} missed={g.missed} total={g.total} />
                          ))
                          : <div className="h-full flex items-center justify-center"><p className="text-sm text-slate-400">No guard data</p></div>
                        }
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* ROW 2: Hourly activity */}
            {stats.hourlyActivity.some(h => h.scans > 0) && (
              <div className="mb-6">
                <div className="glass-panel rounded-3xl p-6">
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">📈 Hourly Activity</h2>
                  <p className="text-xs text-slate-400 mb-4">Successful scans by hour of day</p>
                  <ResponsiveContainer width="100%" height={240}>
                    <AreaChart data={stats.hourlyActivity}>
                      <defs>
                        <linearGradient id="hGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%"  stopColor="#6366f1" stopOpacity={0.3} />
                          <stop offset="95%" stopColor="#6366f1" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
                      <XAxis dataKey="hour" tick={{ fill: '#94a3b8', fontSize: 10 }} axisLine={false} tickLine={false} />
                      <YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12, border: 'none', boxShadow: '0 4px 16px rgba(0,0,0,.1)' }} />
                      <Area type="monotone" dataKey="scans" stroke="#6366f1" strokeWidth={2} fill="url(#hGrad)" dot={false} name="Scans" />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            {/* ROW 3: Guard bar + Scan Point Coverage */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">

              {/* Guard Performance Bar */}
              {stats.guardLeaderboard.length > 0 && (
                <div className={`glass-panel rounded-3xl p-6 ${stats.coverageByPoint.length === 0 ? 'lg:col-span-2' : ''}`}>
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">Guard Scans vs Missed</h2>
                  <p className="text-xs text-slate-400 mb-4">Side-by-side comparison</p>
                  <ResponsiveContainer width="100%" height={240}>
                    <BarChart
                      data={stats.guardLeaderboard.slice(0, 8).map(g => ({
                        name: g.name.split(' ')[0], scanned: g.scanned, missed: g.missed
                      }))}
                      barSize={14}
                    >
                      <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
                      <XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} />
                      <YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12, border: 'none', boxShadow: '0 4px 16px rgba(0,0,0,.1)' }} />
                      <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
                      <Bar dataKey="scanned" fill="#6366f1" radius={[6, 6, 0, 0]} name="Scanned" />
                      <Bar dataKey="missed"  fill="#f43f5e" radius={[6, 6, 0, 0]} name="Missed" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              )}

              {/* Scan Point Coverage */}
              {stats.coverageByPoint.length > 0 && (
                <div className={`glass-panel rounded-3xl p-6 ${stats.guardLeaderboard.length === 0 ? 'lg:col-span-2' : ''}`}>
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">📍 Scan Point Coverage</h2>
                  <p className="text-xs text-slate-400 mb-4">% of rounds scanned per checkpoint</p>
                  <div className="overflow-y-auto max-h-64 pr-1">
                    {stats.coverageByPoint.map((p, i) => (
                      <CoverageBar key={i} name={p.name} done={p.done} total={p.total} />
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* ROW 4: Recent Activity Feed + Missed Points Table */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">

              {/* Recent Activity Feed */}
              {stats.recentActivity.length > 0 && (
                <div className={`glass-panel rounded-3xl p-6 ${stats.coverageByPoint.filter((p: any) => p.done < p.total).length === 0 ? 'lg:col-span-2' : ''}`}>
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">🕐 Recent Activity</h2>
                  <p className="text-xs text-slate-400 mb-4">Last 10 successful scans</p>
                  <div className="space-y-2">
                    {stats.recentActivity.map((r, i) => (
                      <div key={i} className="flex items-center gap-3 py-2 border-b border-slate-50 last:border-0">
                        <div className="w-2 h-2 rounded-full bg-amber-400 flex-shrink-0" />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between">
                            <span className="text-sm font-medium text-slate-700 truncate">{r.qr_name}</span>
                            <span className="text-xs text-slate-400 ml-2 flex-shrink-0">{fmtTime(r.scan_time)}</span>
                          </div>
                          <p className="text-xs text-slate-400">
                            {r.guard_name || 'Unknown'} · Round {r.round}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Missed Points Table */}
              {stats.coverageByPoint.filter(p => p.done < p.total).length > 0 && (
                <div className={`glass-panel rounded-3xl p-6 ${stats.recentActivity.length === 0 ? 'lg:col-span-2' : ''}`}>
                  <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-widest mb-1">⚠️ Problem Checkpoints</h2>
                  <p className="text-xs text-slate-400 mb-4">Scan points with incomplete coverage</p>
                  <div className="overflow-x-auto">
                    <table className="min-w-full text-sm">
                      <thead>
                        <tr className="border-b border-slate-100">
                          <th className="text-left py-2 px-2 text-xs font-semibold text-slate-500 uppercase">Point</th>
                          <th className="text-center py-2 px-2 text-xs font-semibold text-amber-600 uppercase">Done</th>
                          <th className="text-center py-2 px-2 text-xs font-semibold text-rose-600 uppercase">Missed</th>
                          <th className="text-center py-2 px-2 text-xs font-semibold text-slate-400 uppercase">Rate</th>
                        </tr>
                      </thead>
                      <tbody>
                        {stats.coverageByPoint
                          .filter(p => p.done < p.total)
                          .map((p, i) => {
                            const pct = Math.round((p.done / p.total) * 100)
                            return (
                              <tr key={i} className="border-b border-slate-50 hover:bg-slate-50 transition-colors">
                                <td className="py-2 px-2 font-medium text-slate-700 text-xs">{p.name}</td>
                                <td className="py-2 px-2 text-center">
                                  <span className="text-xs font-bold text-amber-600">✓ {p.done}</span>
                                </td>
                                <td className="py-2 px-2 text-center">
                                  <span className="text-xs font-bold text-rose-600">✗ {p.total - p.done}</span>
                                </td>
                                <td className="py-2 px-2 text-center">
                                  <span className={`text-xs font-bold px-1.5 py-0.5 rounded-full ${pct >= 80 ? 'bg-amber-50 text-amber-600' : pct >= 50 ? 'bg-amber-50 text-amber-600' : 'bg-rose-50 text-rose-600'}`}>
                                    {pct}%
                                  </span>
                                </td>
                              </tr>
                            )
                          })}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
            
            {stats.coverageByPoint.filter(p => p.done < p.total).length === 0 && stats.completed > 0 && (
              <div className="glass-panel rounded-3xl p-6 flex flex-col items-center justify-center gap-3 text-amber-600">
                <span className="text-5xl">🎉</span>
                <p className="font-bold text-lg">All checkpoints covered!</p>
                <p className="text-sm text-slate-400">Every scan point has 100% coverage</p>
              </div>
            )}
          </>
        ) : report.length === 0 && !loading ? (
          <div className="glass-panel rounded-3xl min-h-[300px] flex flex-col items-center justify-center gap-3 text-slate-400">
            <span className="text-5xl">📊</span>
            <p className="text-lg font-semibold text-slate-500">No data found</p>
            <p className="text-sm">Select a campus and date, then click Load</p>
          </div>
        ) : loading ? (
          <div className="glass-panel rounded-3xl min-h-[300px] flex items-center justify-center">
            <div className="flex flex-col items-center gap-3 text-slate-400">
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-purple-500 border-t-transparent" />
              <p className="text-sm">Loading report data…</p>
            </div>
          </div>
        ) : null}

        </div>{/* end dashboardContentRef */}

        <p className="mt-8 text-center text-xs text-slate-400">© {new Date().getFullYear()} KCET Security Rounds — Dashboard</p>
      </motion.div>
    </div>
  )
}
