'use client'

import { useState, useEffect, useMemo, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import {
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend,
  BarChart, Bar, XAxis, YAxis, CartesianGrid
} from 'recharts'
import { getPatrolReport, PatrolReportItem } from '../api/report'
import { getShifts } from '../api/shifts.api'
import { fetchQRByCampus } from '../api/qr.api'
import { getSecurityUsers } from '../api/securityUsers.api'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { useAuthGuard } from '@/app/services/auth.guard'
import GuardLeaderboard from '../components/analytics/GuardLeaderboard'
import { LOGO_BASE64 } from '../components/reports/logoBase64'
import {
  Filter, Calendar, UserCheck, Shield, Clock, CheckCircle2,
  AlertTriangle, Activity, ChevronDown, Sparkles
} from 'lucide-react'

/* ================================================================
   TYPES & CONSTANTS
================================================================ */
type DashboardStats = {
  total: number; completed: number; missed: number; pending: number; rate: number
  lastScan: string | null
  roundSummary: { round: string; completed: number; missed: number }[]
  guardLeaderboard: { name: string; scanned: number; missed: number; total: number }[]
  coverageByPoint: { name: string; done: number; total: number }[]
  recentActivity: PatrolReportItem[]
}

const ROUND_TIMES = [
  '00:45', '02:45', '04:45', '06:45', '08:45', '10:45',
  '12:45', '14:45', '16:45', '18:45', '20:45', '22:45'
]

/* ================================================================
   HELPERS
================================================================ */
function fmtTime(t: string | null) {
  if (!t) return '—'
  try { 
    const safeT = t.replace(' ', 'T')
    const d = new Date(safeT)
    return isNaN(d.getTime()) ? t : d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) 
  }
  catch { return t }
}

function exportDashboardPDF(
  statsData: DashboardStats,
  campus: string,
  campusName: string,
  dateStr: string,
  adminName: string
) {
  const btn = document.getElementById('pdf-export-btn')
  if (btn) { btn.textContent = '⏳ Generating…'; btn.setAttribute('disabled', 'true') }

  try {
    const doc = new jsPDF()
    const w = doc.internal.pageSize.getWidth()
    const h = doc.internal.pageSize.getHeight()

    const drawBorder = () => {
      doc.setDrawColor(109, 40, 217)
      doc.setLineWidth(0.8)
      doc.rect(8, 8, w - 16, h - 16)
    }
    drawBorder()

    // ========== HEADER ==========
    try {
      doc.addImage(LOGO_BASE64, "JPEG", 14, 12, 28, 28);
    } catch (e) {
      console.warn("Could not load logo", e);
    }
    
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(109, 40, 217)
    doc.setFontSize(20)
    doc.text('Security Patrol Analytics Report', w / 2, 22, { align: 'center' })
    doc.setFontSize(14)
    doc.text(campusName.toUpperCase(), w / 2, 32, { align: 'center' })
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(109, 40, 217)
    doc.text(`Patrol Date : ${dateStr}`, 14, 44)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(40)
    doc.text(`Generated By : ${adminName}`, 14, 51)
    doc.text(`Generated At : ${new Date().toLocaleString()}`, 14, 57)

    let y = 68

    // ========== SUMMARY STATS ==========
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(109, 40, 217)
    doc.text('1. Key Metrics Summary', 14, y)
    doc.line(14, y + 2, w - 14, y + 2)
    y += 8

    autoTable(doc, {
      startY: y,
      margin: { left: 14, right: 14 },
      theme: 'grid',
      headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: 'bold' },
      head: [['Metric', 'Value']],
      body: [
        ['Total Effective Scans (Due)', String(statsData.total)],
        ['Completed Scans (Success)', String(statsData.completed)],
        ['Missed Scans', String(statsData.missed)],
        ['Not Due Yet (Pending)', String(statsData.pending)],
        ['Completion Rate (%)', `${statsData.rate}%`],
        ['Last Scan Recorded', statsData.lastScan ? fmtTime(statsData.lastScan) : 'N/A'],
      ],
    })

    y = (doc as any).lastAutoTable.finalY + 12

    // ========== GUARD LEADERBOARD ==========
    if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(109, 40, 217)
    doc.text('2. Security Guard Performance', 14, y)
    doc.line(14, y + 2, w - 14, y + 2)
    y += 8

    const guardRows = statsData.guardLeaderboard.map((g, i) => [
      `#${i + 1}`,
      g.name,
      String(g.scanned),
      String(g.missed),
      String(g.total),
      `${Math.round((g.scanned / (g.total || 1)) * 100)}%`,
    ])

    autoTable(doc, {
      startY: y,
      margin: { left: 14, right: 14 },
      theme: 'striped',
      headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: 'bold' },
      head: [['Rank', 'Guard Name', 'Completed', 'Missed', 'Total', 'Compliance Rate']],
      body: guardRows.length > 0 ? guardRows : [['—', 'No activity logged', '0', '0', '0', '0%']],
    })

    y = (doc as any).lastAutoTable.finalY + 12

    // ========== ROUND SUMMARY ==========
    if (y > h - 60) { doc.addPage(); drawBorder(); y = 20 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(109, 40, 217)
    doc.text('3. Patrol Rounds Breakdown', 14, y)
    doc.line(14, y + 2, w - 14, y + 2)
    y += 8

    const roundRows = statsData.roundSummary.map(r => [
      `Round ${r.round}`,
      String(r.completed),
      String(r.missed),
      String(r.completed + r.missed),
    ])

    autoTable(doc, {
      startY: y,
      margin: { left: 14, right: 14 },
      theme: 'striped',
      headStyles: { fillColor: [109, 40, 217], textColor: 255, fontStyle: 'bold' },
      head: [['Round Slot', 'Completed', 'Missed', 'Total Due']],
      body: roundRows.length > 0 ? roundRows : [['—', '0', '0', '0']],
    })

    // ========== FOOTER ==========
    const totalPages = (doc as any).internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(120)
      doc.text(
        `KCET Security Patrol Management System | Confidential | Page ${i} of ${totalPages}`,
        w / 2, h - 12, { align: 'center' }
      )
    }

    doc.save(`KCET_Patrol_Analytics_${dateStr}.pdf`)
  } catch (err) {
    console.error('PDF export error:', err)
    alert('Failed to generate PDF. Check console.')
  } finally {
    if (btn) { btn.textContent = '📊 Export PDF'; btn.removeAttribute('disabled') }
  }
}

/* ── STAT CARD COMPONENT ── */
function StatCard({ label, value, sub, color, bg, icon }: {
  label: string; value: number | string; sub: string; color: string; bg: string; icon: string
}) {
  return (
    <div className="glass-card rounded-2xl p-5 flex flex-col justify-between relative overflow-hidden">
      <div className="flex items-center justify-between">
        <span className="text-xs font-bold uppercase tracking-wider text-purple-400">{label}</span>
        <span className="text-xl">{icon}</span>
      </div>
      <div className="mt-3">
        <div className={`text-3xl font-extrabold ${color}`}>{value}</div>
        <p className="text-xs text-slate-400 mt-0.5 font-medium">{sub}</p>
      </div>
    </div>
  )
}

export default function DashboardPage() {
  const router = useRouter()
  const { authorized } = useAuthGuard({ allowedRoles: ['ADMIN'] });

  const todayStr = useMemo(() => {
    const d = new Date();
    const offset = d.getTimezoneOffset() * 60000;
    return new Date(d.getTime() - offset).toISOString().slice(0, 10);
  }, [])

  const [adminName, setAdminName]             = useState('')
  const FIXED_CAMPUS                          = 'KCET01'
  
  // ── SINGLE DATE STATE ──
  const [selectedDate, setSelectedDate]       = useState(todayStr)
  const [activePreset, setActivePreset]       = useState<'today' | 'yesterday' | 'custom'>('today')

  const [report, setReport]                   = useState<PatrolReportItem[]>([])
  const [shifts, setShifts]                   = useState<any[]>([])
  const [qrs, setQrs]                         = useState<any[]>([])
  const [secUsers, setSecUsers]               = useState<any[]>([])
  const [loading, setLoading]                 = useState(false)
  const [lastUpdated, setLastUpdated]         = useState('')

  // ── FILTER STATES ──
  const [selectedGuard, setSelectedGuard]     = useState('ALL')
  const [selectedRound, setSelectedRound]     = useState('ALL')
  const [selectedStatus, setSelectedStatus]   = useState('ALL')

  /* auth check */
  useEffect(() => {
    if (authorized) {
      const name = localStorage.getItem('adminName') || ''
      setAdminName(name)
    }
  }, [authorized])

  /* ── FETCH LOGIC WITH SILENT REFRESH SUPPORT ── */
  const fetchReportAndShifts = useCallback((showLoading = true) => {
    if (!authorized || !selectedDate) return
    if (showLoading) setLoading(true)
    
    Promise.all([
      getPatrolReport(FIXED_CAMPUS, selectedDate),
      getShifts(),
      fetchQRByCampus(FIXED_CAMPUS),
      getSecurityUsers()
    ])
      .then(([reportData, shiftsData, qrsData, usersData]) => {
        setReport(reportData || [])
        setShifts(shiftsData || [])
        setQrs(qrsData || [])
        setSecUsers(usersData || [])
        setLastUpdated(new Date().toLocaleTimeString())
      })
      .catch(() => { 
        if (showLoading) { setReport([]); setShifts([]); setQrs([]); setSecUsers([]) }
      })
      .finally(() => { if (showLoading) setLoading(false) })
  }, [selectedDate, authorized])

  /* auto-fetch when selectedDate changes */
  useEffect(() => {
    fetchReportAndShifts(true)
  }, [fetchReportAndShifts])

  /* ── SILENT BACKGROUND POLLING (Every 10 seconds silently) ── */
  useEffect(() => {
    if (!authorized || !selectedDate) return
    const interval = setInterval(() => {
      fetchReportAndShifts(false)
    }, 10000)
    return () => clearInterval(interval)
  }, [fetchReportAndShifts, authorized, selectedDate])

  /* ── DATE SHORTCUT HANDLERS ── */
  const setPresetDate = (type: 'today' | 'yesterday') => {
    setActivePreset(type)
    const now = new Date()
    const offset = now.getTimezoneOffset() * 60000
    const localNow = new Date(now.getTime() - offset)
    const tStr = localNow.toISOString().slice(0, 10)

    if (type === 'today') {
      setSelectedDate(tStr)
    } else if (type === 'yesterday') {
      const yest = new Date(localNow.getTime() - 86400000)
      setSelectedDate(yest.toISOString().slice(0, 10))
    }
  }

  /* ── COMBINED GUARD LIST FOR DROPDOWN (REGISTERED + REPORT GUARDS) ── */
  const availableGuards = useMemo(() => {
    const guardsSet = new Set<string>()
    secUsers.forEach(u => {
      if (u.security_name && u.security_name.toUpperCase() !== 'SYSTEM_MISSED') {
        guardsSet.add(u.security_name.trim())
      }
    })
    report.forEach(r => {
      if (r.guard_name && r.guard_name.toUpperCase() !== 'SYSTEM_MISSED') {
        r.guard_name.split(',').forEach(g => {
          if (g.toUpperCase() !== 'SYSTEM_MISSED') guardsSet.add(g.trim())
        })
      }
    })
    return Array.from(guardsSet).sort()
  }, [secUsers, report])

  /* ── HELPER: MATCH GUARD NAME FLEXIBLY ── */
  const isMatchGuard = (guardName: string | null | undefined, selected: string) => {
    if (selected === 'ALL') return true
    if (!guardName) return false
    if (guardName === 'SYSTEM_MISSED') return true
    const sLower = selected.toLowerCase().trim()
    const gLower = guardName.toLowerCase().trim()
    return gLower.includes(sLower) || sLower.includes(gLower)
  }

  /* ── COMPUTED STATS (time-aware for past dates vs today) ── */
  const stats = useMemo(() => {
    const isToday = (selectedDate === todayStr)
    const isPastDate = (selectedDate < todayStr)

    // Filter report according to user selection
    const filteredReport = report.filter(r => {
      if (selectedGuard !== 'ALL') {
        if (!isMatchGuard(r.guard_name, selectedGuard)) return false
      }
      if (selectedRound !== 'ALL' && r.round !== Number(selectedRound)) {
        return false
      }
      if (selectedStatus !== 'ALL' && r.status !== selectedStatus) {
        return false
      }
      return true
    })

    const selectedDateEnd = new Date(`${selectedDate}T23:59:59.999`);
    const activeQRsOnDate = qrs.filter((q: any) => {
      if (q.campus_code && q.campus_code !== FIXED_CAMPUS) return false;
      const createdDate = new Date(q.created_at);
      return createdDate <= selectedDateEnd;
    });
    const targetScansPerRound = activeQRsOnDate.length;

    let dueRoundsCount = ROUND_TIMES.length;
    let activeRoundIndex = -1;

    if (isToday) {
      const now = new Date();
      const currentHour = now.getHours();
      const currentMinute = now.getMinutes();
      dueRoundsCount = 0;
      const currentMins = currentHour * 60 + currentMinute

      for (let i = 0; i < ROUND_TIMES.length; i++) {
        const h = parseInt(ROUND_TIMES[i].split(':')[0]);
        const startMins = h * 60 + 45;
        const endMins = h * 60 + 90;

        if (currentMins >= startMins && currentMins < endMins) {
          activeRoundIndex = i;
        }

        if (currentHour > h + 1 || (currentHour === h + 1 && currentMinute >= 30)) {
          dueRoundsCount = i + 1;
        } else if (currentMins < startMins) {
          break;
        }
      }
    }

    const scannedRounds = filteredReport.filter(r => r.scan_time !== null).map(r => r.round)
    const maxScannedRound = scannedRounds.length ? Math.max(...scannedRounds) : 0
    const nothingScannedToday = isToday && maxScannedRound === 0

    // Effective records evaluation:
    // For past dates: All 12 rounds are due! pending = 0
    // For today: Only rounds due so far or scanned success are effective
    const effective = isToday
      ? filteredReport.filter(r => r.round <= dueRoundsCount || r.status === 'SUCCESS')
      : filteredReport

    const pending = isToday ? (filteredReport.length - effective.length) : 0

    /* base stats */
    const completed = effective.filter(r => r.status === 'SUCCESS').length
    const missed    = (isToday && nothingScannedToday) ? 0 : effective.filter(r => r.status === 'MISSED').length
    const total     = completed + missed
    const rate      = total ? Math.round((completed / total) * 100) : 0

    /* last scan time */
    const scanTimes = effective.filter(r => r.scan_time).map(r => r.scan_time as string).sort()
    const lastScan  = scanTimes.length ? scanTimes[scanTimes.length - 1] : null

    /* pie chart data */
    const pie = [
      { name: 'Completed', value: completed, color: '#6d28d9' },
      { name: 'Missed',    value: missed,    color: '#e11d48' },
      ...(pending > 0 ? [{ name: 'Not Due Yet', value: pending, color: '#94a3b8' }] : []),
    ]

    /* rounds summary */
    const roundNums = [...new Set(effective.map(r => r.round))].sort((a, b) => a - b)
    const roundSummary = (isToday && nothingScannedToday) ? [] : roundNums.map(rnd => {
      const items = effective.filter(r => r.round === rnd)
      return {
        round: `Round ${rnd}`,
        completed: items.filter(r => r.status === 'SUCCESS').length,
        missed: items.filter(r => r.status === 'MISSED').length,
      }
    })

    /* guard leaderboard */
    const overallGuardMap: Record<string, { scanned: number; missed: number }> = {}
    effective.forEach(r => {
      if (r.status === 'SUCCESS' || (!nothingScannedToday && r.status === 'MISSED')) {
        let rawGuard = r.guard_name;
        if (!rawGuard || rawGuard.toUpperCase() === 'SYSTEM_MISSED') {
          if (r.round === 6 || r.round === 9) rawGuard = 'GOKUL';
          else if (r.round === 7 || r.round === 8) rawGuard = 'SAKTHI VEL C';
          else rawGuard = 'Allotted Guard';
        }
        const guardsList = rawGuard.split(',').map(name => name.trim()).filter(Boolean);
        guardsList.forEach(g => {
          if (g.toUpperCase() === 'SYSTEM_MISSED' || g.toLowerCase() === 'unknown') return;
          if (!overallGuardMap[g]) overallGuardMap[g] = { scanned: 0, missed: 0 };
          if (r.status === 'SUCCESS') overallGuardMap[g].scanned++;
          else overallGuardMap[g].missed++;
        });
      }
    })
    const guardLeaderboard = Object.entries(overallGuardMap)
      .filter(([n, d]) => n !== 'Unknown' && n.toUpperCase() !== 'SYSTEM_MISSED')
      .map(([name, d]) => ({ name, ...d, total: d.scanned + d.missed }))
      .sort((a, b) => b.scanned / (b.total || 1) - a.scanned / (a.total || 1))

    /* point coverage */
    const pointMap: Record<string, { done: number; total: number }> = {}
    effective.forEach(r => {
      if (!pointMap[r.qr_name]) pointMap[r.qr_name] = { done: 0, total: 0 }
      pointMap[r.qr_name].total++
      if (r.status === 'SUCCESS') pointMap[r.qr_name].done++
    })
    const coverageByPoint = Object.entries(pointMap)
      .map(([name, v]) => ({ name, ...v }))
      .sort((a, b) => (a.done / a.total) - (b.done / b.total))

    /* timeline cards */
    const timeline = ROUND_TIMES.map((time, idx) => {
      const roundNo = idx + 1;
      const h = parseInt(time.split(':')[0]);
      
      let status: 'COMPLETED' | 'PARTIAL' | 'MISSED' | 'ACTIVE' | 'PENDING' = 'PENDING';
      let isActive = (activeRoundIndex === idx);
      
      const items = filteredReport.filter(r => r.round === roundNo);
      const successCount = items.filter(r => r.status === 'SUCCESS').length;
      
      const isSuccess = successCount >= targetScansPerRound && targetScansPerRound > 0;
      const isPartial = successCount > 0 && successCount < targetScansPerRound;
      
      if (isToday) {
        const now = new Date();
        const currentMins = now.getHours() * 60 + now.getMinutes();
        const endMins = h * 60 + 90;
        const isPast = currentMins >= endMins;
        
        if (isSuccess) status = 'COMPLETED';
        else if (isPartial) status = 'PARTIAL';
        else if (isActive) status = 'ACTIVE';
        else if (isPast) status = 'MISSED';
        else status = 'PENDING';
      } else {
        if (isSuccess) status = 'COMPLETED';
        else if (isPartial) status = 'PARTIAL';
        else status = 'MISSED';
      }
      
      return {
        roundNo,
        timeLabel: `${String(h).padStart(2, '0')}:00 - ${String(h + 2).padStart(2, '0')}:00`,
        status,
        scannedCount: successCount,
        totalTarget: targetScansPerRound
      };
    });

    /* Active round detail info */
    const activeRoundInfo = activeRoundIndex >= 0 ? {
      roundNo: activeRoundIndex + 1,
      timeLabel: `${String(ROUND_TIMES[activeRoundIndex]).split(':')[0]}:45 - ${String(parseInt(ROUND_TIMES[activeRoundIndex].split(':')[0]) + 1).padStart(2, '0')}:30`,
      items: filteredReport.filter(r => r.round === activeRoundIndex + 1),
      completed: filteredReport.filter(r => r.round === activeRoundIndex + 1 && r.status === 'SUCCESS').length,
      target: targetScansPerRound
    } : null

    return {
      total, completed, missed, pending, rate, lastScan, pie, roundSummary,
      shiftLeaderboards: [], guardLeaderboard, coverageByPoint, hourlyActivity: [], recentActivity: [],
      nothingScannedToday, timeline, activeRoundInfo
    }
  }, [report, selectedDate, todayStr, selectedGuard, selectedRound, selectedStatus, qrs])

  const selectedCampusName = "KCET Main Campus"

  if (!authorized) {
    return <div className="p-6 text-slate-500 min-h-screen flex items-center justify-center">Checking access...</div>
  }

  return (
    <div className="min-h-screen relative font-sans text-slate-900 selection:bg-purple-100 selection:text-purple-900">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
        className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 relative z-10 space-y-6"
      >

        {/* ── HEADER ── */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <p className="section-heading">Live Analytics</p>
            <h1 className="text-3xl font-extrabold tracking-tight text-purple-950">
              Patrol <span className="text-gradient">Dashboard</span>
            </h1>
            <p className="mt-1 text-slate-500 text-sm flex items-center gap-2">
              <span className="font-semibold text-purple-700">{selectedCampusName}</span>
              {' · '}
              <span>Date: <strong className="text-slate-800">{selectedDate}</strong></span>
              {lastUpdated && (
                <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                  Live Sync ({lastUpdated})
                </span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-2 px-3.5 py-2 glass-panel rounded-2xl text-xs font-semibold text-purple-950 border border-purple-100 shadow-sm">
            <Shield size={15} className="text-purple-600" />
            <span>Admin: {adminName || 'Admin User'}</span>
          </div>
        </div>

        {/* ── LIVE ACTIVE ROUND PROGRESS BAR ── */}
        {stats.activeRoundInfo && (
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            className="glass-panel border-l-4 border-l-purple-600 rounded-3xl p-5 bg-gradient-to-r from-purple-50/70 via-white to-white shadow-xl shadow-purple-900/5"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-3.5">
                <div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-purple-600 to-violet-700 text-white flex items-center justify-center font-extrabold shadow-lg shadow-purple-500/30 text-base">
                  R{stats.activeRoundInfo.roundNo}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-extrabold text-purple-950 text-base">Round {stats.activeRoundInfo.roundNo} In Progress</h3>
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-extrabold bg-purple-100 text-purple-800 border border-purple-200 animate-pulse">
                      <Activity size={12} /> ONGOING
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 font-medium mt-0.5">
                    Window: {stats.activeRoundInfo.timeLabel} · Patrol active
                  </p>
                </div>
              </div>

              {/* Progress meter */}
              <div className="flex items-center gap-4 min-w-[220px] sm:min-w-[280px]">
                <div className="flex-1">
                  <div className="flex justify-between text-xs font-bold text-slate-700 mb-1.5">
                    <span>Scan Progress</span>
                    <span className="text-purple-700">{stats.activeRoundInfo.completed} / {stats.activeRoundInfo.target} Scanned</span>
                  </div>
                  <div className="w-full h-3 bg-purple-100 rounded-full overflow-hidden p-0.5 border border-purple-200/60">
                    <div
                      className="h-full bg-gradient-to-r from-purple-600 to-violet-500 rounded-full transition-all duration-500"
                      style={{ width: `${Math.round((stats.activeRoundInfo.completed / (stats.activeRoundInfo.target || 1)) * 100)}%` }}
                    />
                  </div>
                </div>
                <span className="text-xl font-black text-purple-950 min-w-[48px] text-right">
                  {Math.round((stats.activeRoundInfo.completed / (stats.activeRoundInfo.target || 1)) * 100)}%
                </span>
              </div>
            </div>
          </motion.div>
        )}

        {/* ── CONTROLS & FILTERING BAR (PREMIUM STYLED) ── */}
        <div className="glass-panel rounded-3xl p-6 space-y-5 border border-purple-100/80 shadow-xl shadow-purple-900/5">
          
          {/* Header & Date Preset Pills */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-purple-100/60 pb-4">
            <div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-widest text-purple-600">
              <Sparkles size={16} className="text-amber-500" /> Dashboard Analytics Controls
            </div>

            {/* Glowing Preset Pills for Single Dates */}
            <div className="flex flex-wrap items-center gap-2">
              {[
                { label: 'Today', key: 'today', icon: <Clock size={13} /> },
                { label: 'Yesterday', key: 'yesterday', icon: <Calendar size={13} /> },
              ].map(preset => {
                const isActive = activePreset === preset.key
                return (
                  <motion.button
                    key={preset.key}
                    whileHover={{ scale: 1.04 }}
                    whileTap={{ scale: 0.96 }}
                    onClick={() => setPresetDate(preset.key as any)}
                    className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-bold transition-all ${
                      isActive
                        ? 'bg-gradient-to-r from-purple-600 to-violet-700 text-white shadow-md shadow-purple-500/30 ring-2 ring-purple-400/40'
                        : 'bg-white/80 hover:bg-purple-50 text-slate-600 hover:text-purple-700 border border-purple-100'
                    }`}
                  >
                    {preset.icon}
                    {preset.label}
                  </motion.button>
                )
              })}
            </div>
          </div>

          {/* Controls Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-12 gap-4 items-end">
            
            {/* Single Specific Date Selector */}
            <div className="lg:col-span-3 space-y-1.5">
              <label className="text-[11px] font-bold uppercase tracking-widest text-purple-400 flex items-center gap-1">
                <Calendar size={13} /> Select Specific Date
              </label>
              <input
                type="date"
                value={selectedDate}
                onChange={e => { setSelectedDate(e.target.value); setActivePreset('custom') }}
                className="input-field py-2.5 text-xs font-semibold text-purple-950 bg-white/90"
              />
            </div>

            {/* Guard Filter */}
            <div className="lg:col-span-3 space-y-1.5">
              <label className="text-[11px] font-bold uppercase tracking-widest text-purple-400 flex items-center gap-1">
                <UserCheck size={13} /> Officer
              </label>
              <div className="relative">
                <select
                  value={selectedGuard}
                  onChange={e => setSelectedGuard(e.target.value)}
                  className="input-field py-2.5 text-xs bg-white/90 cursor-pointer font-bold text-purple-950 pr-8 appearance-none"
                >
                  <option value="ALL">All Officers</option>
                  {availableGuards.map(g => (
                    <option key={g} value={g}>{g}</option>
                  ))}
                </select>
                <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-purple-400 pointer-events-none" />
              </div>
            </div>

            {/* Round Filter */}
            <div className="lg:col-span-2 space-y-1.5">
              <label className="text-[11px] font-bold uppercase tracking-widest text-purple-400 flex items-center gap-1">
                <Clock size={13} /> Round Slot
              </label>
              <div className="relative">
                <select
                  value={selectedRound}
                  onChange={e => setSelectedRound(e.target.value)}
                  className="input-field py-2.5 text-xs bg-white/90 cursor-pointer font-bold text-purple-950 pr-8 appearance-none"
                >
                  <option value="ALL">All Rounds</option>
                  {ROUND_TIMES.map((_, idx) => (
                    <option key={idx + 1} value={idx + 1}>Round {idx + 1}</option>
                  ))}
                </select>
                <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-purple-400 pointer-events-none" />
              </div>
            </div>

            {/* Status Filter */}
            <div className="lg:col-span-2 space-y-1.5">
              <label className="text-[11px] font-bold uppercase tracking-widest text-purple-400 flex items-center gap-1">
                <CheckCircle2 size={13} /> Status
              </label>
              <div className="relative">
                <select
                  value={selectedStatus}
                  onChange={e => setSelectedStatus(e.target.value)}
                  className="input-field py-2.5 text-xs bg-white/90 cursor-pointer font-bold text-purple-950 pr-8 appearance-none"
                >
                  <option value="ALL">All Statuses</option>
                  <option value="SUCCESS">Completed (Success)</option>
                  <option value="MISSED">Missed</option>
                </select>
                <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-purple-400 pointer-events-none" />
              </div>
            </div>

            {/* Actions */}
            <div className="lg:col-span-2 flex items-center gap-2">
              <button
                id="pdf-export-btn"
                onClick={() => exportDashboardPDF(stats, FIXED_CAMPUS, selectedCampusName, selectedDate, adminName)}
                className="btn-primary py-2.5 px-3 text-xs w-full justify-center flex items-center gap-1.5 shadow-md shadow-purple-500/20"
              >
                📊 Export PDF
              </button>
            </div>

          </div>
        </div>

        {/* ── STAT CARDS ── */}
        <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">
          <StatCard label="Effective Scans"  value={stats.total}        sub="Due in window"      color="text-purple-700"  bg="bg-purple-500"  icon="📋" />
          <StatCard label="Completed"        value={stats.completed}    sub={`${stats.rate}% completion`} color="text-emerald-700" bg="bg-emerald-500" icon="✅" />
          <StatCard label="Missed"           value={stats.missed}       sub="Uncompleted rounds" color="text-rose-700"    bg="bg-rose-500"    icon="⚠️" />
          <StatCard label="Not Due Yet"      value={stats.pending ?? 0} sub="Scheduled later"    color="text-slate-500"   bg="bg-slate-400"   icon="🕐" />
        </div>

        {/* ── CHARTS SECTION ── */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Pie Chart */}
          <div className="lg:col-span-5 glass-panel rounded-3xl p-6 flex flex-col justify-between">
            <div className="border-b border-purple-100/60 pb-3 mb-4">
              <p className="section-heading">Distribution</p>
              <h3 className="text-base font-extrabold text-purple-950">Patrol Completion Ratio</h3>
            </div>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={stats.pie}
                    cx="50%" cy="50%"
                    innerRadius={55} outerRadius={85}
                    paddingAngle={4}
                    dataKey="value"
                  >
                    {stats.pie.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend verticalAlign="bottom" height={36} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Rounds Bar Chart */}
          <div className="lg:col-span-7 glass-panel rounded-3xl p-6 flex flex-col justify-between">
            <div className="border-b border-purple-100/60 pb-3 mb-4 flex items-center justify-between">
              <div>
                <p className="section-heading">Round Activity</p>
                <h3 className="text-base font-extrabold text-purple-950">Completed vs Missed Scans per Round</h3>
              </div>
            </div>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={stats.roundSummary}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f1f0fe" />
                  <XAxis dataKey="round" stroke="#6b5f8a" fontSize={11} />
                  <YAxis stroke="#6b5f8a" fontSize={11} />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="completed" name="Completed" fill="#6d28d9" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="missed" name="Missed" fill="#e11d48" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* ── GUARD LEADERBOARD COMPONENT ── */}
        <GuardLeaderboard guards={stats.guardLeaderboard} />

        {/* ── PATROL TIMELINE ── */}
        <div className="glass-panel rounded-3xl p-6 sm:p-8 space-y-5">
          <div className="border-b border-purple-100/60 pb-4">
            <p className="section-heading">Daily Schedule</p>
            <h2 className="text-xl font-extrabold text-purple-950">Patrol Rounds Status Timeline</h2>
            <p className="text-xs text-slate-500 mt-0.5">Status of 12 daily patrol windows</p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-6 gap-3">
            {stats.timeline.map(t => {
              const isCompleted = t.status === 'COMPLETED'
              const isPartial = t.status === 'PARTIAL'
              const isActive = t.status === 'ACTIVE'
              const isMissed = t.status === 'MISSED'

              return (
                <div
                  key={t.roundNo}
                  className={`rounded-2xl p-4 border transition-all ${
                    isCompleted ? 'bg-emerald-50/70 border-emerald-200 text-emerald-950' :
                    isPartial ? 'bg-amber-50/70 border-amber-200 text-amber-950' :
                    isActive ? 'bg-purple-100/80 border-purple-300 text-purple-950 ring-2 ring-purple-400/40' :
                    isMissed ? 'bg-rose-50/70 border-rose-200 text-rose-950' :
                    'bg-slate-50 border-slate-200 text-slate-500'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-extrabold text-xs">Round {t.roundNo}</span>
                    {isCompleted && <CheckCircle2 size={15} className="text-emerald-600" />}
                    {isMissed && <AlertTriangle size={15} className="text-rose-600" />}
                    {isActive && <Activity size={15} className="text-purple-600 animate-pulse" />}
                  </div>
                  <p className="text-[11px] font-semibold opacity-75">{t.timeLabel}</p>
                  <div className="mt-3">
                    <span className={`inline-block px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                      isCompleted ? 'bg-emerald-100 text-emerald-800' :
                      isPartial ? 'bg-amber-100 text-amber-800' :
                      isActive ? 'bg-purple-200 text-purple-800 animate-pulse' :
                      isMissed ? 'bg-rose-100 text-rose-800' :
                      'bg-slate-200 text-slate-600'
                    }`}>
                      {t.status}
                    </span>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

      </motion.div>
    </div>
  )
}
